markettor/temporal/common/utils.py:0: error: Argument 1 to "abstractclassmethod" has incompatible type "Callable[[HeartbeatDetails, Any], Any]"; expected "Callable[[type[Never], Any], Any]"  [arg-type]
markettor/temporal/common/utils.py:0: note: This is likely because "from_activity" has named arguments: "cls". Consider marking them positional-only
markettor/temporal/common/utils.py:0: error: Argument 2 to "__get__" of "classmethod" has incompatible type "type[HeartbeatType]"; expected "type[Never]"  [arg-type]
markettor/tasks/exports/ordered_csv_renderer.py:0: error: No return value expected  [return-value]
markettor/warehouse/models/ssh_tunnel.py:0: error: Incompatible types in assignment (expression has type "NoEncryption", variable has type "BestAvailableEncryption")  [assignment]
markettor/utils.py:0: error: No overload variant of "asdict" matches argument type "type[DataclassInstance]"  [call-overload]
markettor/utils.py:0: note: Possible overload variants:
markettor/utils.py:0: note: def asdict(obj: DataclassInstance) -> dict[str, Any]
markettor/utils.py:0: note: def [_T] asdict(obj: DataclassInstance, *, dict_factory: Callable[[list[tuple[str, Any]]], _T]) -> _T
markettor/utils.py:0: error: Name "timezone.datetime" is not defined  [name-defined]
markettor/settings/data_stores.py:0: error: Incompatible types in assignment (expression has type "str | None", variable has type "str")  [assignment]
markettor/settings/data_stores.py:0: error: Name "DATABASE_URL" already defined on line 0  [no-redef]
markettor/plugins/utils.py:0: error: Subclass of "str" and "bytes" cannot exist: would have incompatible method signatures  [unreachable]
markettor/plugins/utils.py:0: error: Statement is unreachable  [unreachable]
markettor/models/dashboard.py:0: error: Need type annotation for "insights"  [var-annotated]
markettor/hogql/database/schema/numbers.py:0: error: Incompatible types in assignment (expression has type "dict[str, IntegerDatabaseField]", variable has type "dict[str, FieldOrTable]")  [assignment]
markettor/hogql/database/schema/numbers.py:0: note: "Dict" is invariant -- see https://mypy.readthedocs.io/en/stable/common_issues.html#variance
markettor/hogql/database/schema/numbers.py:0: note: Consider using "Mapping" instead, which is covariant in the value type
markettor/hogql/ast.py:0: error: Incompatible return value type (got "bool | None", expected "bool")  [return-value]
markettor/warehouse/data_load/service.py:0: error: Unsupported operand types for >= ("timedelta" and "None")  [operator]
markettor/warehouse/data_load/service.py:0: note: Left operand is of type "timedelta | None"
markettor/warehouse/data_load/service.py:0: error: Incompatible return value type (got "tuple[timedelta | None, timedelta]", expected "tuple[timedelta, timedelta]")  [return-value]
markettor/warehouse/data_load/service.py:0: error: Unsupported operand types for >= ("timedelta" and "None")  [operator]
markettor/warehouse/data_load/service.py:0: note: Left operand is of type "timedelta | None"
markettor/warehouse/data_load/service.py:0: error: Incompatible return value type (got "tuple[timedelta | None, timedelta]", expected "tuple[timedelta, timedelta]")  [return-value]
markettor/warehouse/data_load/service.py:0: error: Incompatible return value type (got "tuple[timedelta | None, timedelta]", expected "tuple[timedelta, timedelta]")  [return-value]
markettor/tasks/tasks.py:0: error: Module "django.utils.timezone" does not explicitly export attribute "timedelta"  [attr-defined]
markettor/models/subscription.py:0: error: Argument 2 to "SubscriptionResourceInfo" has incompatible type "str | None"; expected "str"  [arg-type]
markettor/models/exported_asset.py:0: error: Value of type variable "_StrOrPromiseT" of "slugify" cannot be "str | None"  [type-var]
markettor/models/action/action.py:0: error: Need type annotation for "events"  [var-annotated]
markettor/models/action/action.py:0: error: Argument 1 to "len" has incompatible type "str | None"; expected "Sized"  [arg-type]
markettor/hogql/visitor.py:0: error: Incompatible types in assignment (expression has type "Expr", variable has type "CTE")  [assignment]
markettor/hogql/visitor.py:0: error: Incompatible types in assignment (expression has type "Expr", variable has type "CTE")  [assignment]
markettor/hogql/visitor.py:0: error: Incompatible types in assignment (expression has type "Expr", variable has type "CTE")  [assignment]
markettor/hogql/visitor.py:0: error: Incompatible types in assignment (expression has type "OrderExpr", variable has type "CTE")  [assignment]
markettor/hogql/visitor.py:0: error: Incompatible types in assignment (expression has type "Expr", variable has type "CTE")  [assignment]
markettor/hogql/visitor.py:0: error: Incompatible types in assignment (expression has type "WindowExpr", variable has type "CTE")  [assignment]
markettor/hogql/visitor.py:0: error: Incompatible types in assignment (expression has type "FieldAliasType", variable has type "BaseTableType | SelectUnionQueryType | SelectQueryType | SelectQueryAliasType | SelectViewType")  [assignment]
markettor/hogql/visitor.py:0: error: Incompatible types in assignment (expression has type "Type", variable has type "BaseTableType | SelectUnionQueryType | SelectQueryType | SelectQueryAliasType | SelectViewType")  [assignment]
ee/models/license.py:0: error: Incompatible return value type (got "_T", expected "License | None")  [return-value]
ee/models/license.py:0: error: Cannot use a covariant type variable as a parameter  [misc]
ee/models/license.py:0: error: "_T" has no attribute "plan"  [attr-defined]
ee/models/license.py:0: error: Incompatible return value type (got "str | bool", expected "bool")  [return-value]
ee/models/explicit_team_membership.py:0: error: Incompatible return value type (got "int", expected "Level")  [return-value]
markettor/hogql/resolver_utils.py:0: error: Argument 1 to "lookup_field_by_name" has incompatible type "SelectQueryType | SelectUnionQueryType"; expected "SelectQueryType"  [arg-type]
markettor/models/filters/mixins/simplify.py:0: error: Incompatible type for lookup 'pk': (got "str | int | list[str]", expected "str | int")  [misc]
markettor/hogql/parser.py:0: error: Item "None" of "list[Expr] | None" has no attribute "__iter__" (not iterable)  [union-attr]
markettor/hogql/parser.py:0: error: "None" has no attribute "text"  [attr-defined]
markettor/hogql/parser.py:0: error: "None" has no attribute "text"  [attr-defined]
markettor/hogql/parser.py:0: error: Statement is unreachable  [unreachable]
markettor/helpers/dashboard_templates.py:0: error: Incompatible types in assignment (expression has type "str | None", variable has type "str | Combinable")  [assignment]
markettor/hogql/functions/cohort.py:0: error: Incompatible type for lookup 'team_id': (got "int | None", expected "str | int")  [misc]
markettor/hogql/functions/cohort.py:0: error: Incompatible type for lookup 'team_id': (got "int | None", expected "str | int")  [misc]
markettor/hogql/database/schema/persons_pdi.py:0: error: Incompatible types in assignment (expression has type "Organization | None", variable has type "Organization")  [assignment]
markettor/hogql/database/schema/groups.py:0: error: Incompatible types in assignment (expression has type "dict[str, DatabaseField]", variable has type "dict[str, FieldOrTable]")  [assignment]
markettor/hogql/database/schema/groups.py:0: note: "Dict" is invariant -- see https://mypy.readthedocs.io/en/stable/common_issues.html#variance
markettor/hogql/database/schema/groups.py:0: note: Consider using "Mapping" instead, which is covariant in the value type
markettor/hogql/database/schema/groups.py:0: error: Incompatible types in assignment (expression has type "dict[str, DatabaseField]", variable has type "dict[str, FieldOrTable]")  [assignment]
markettor/hogql/database/schema/groups.py:0: note: "Dict" is invariant -- see https://mypy.readthedocs.io/en/stable/common_issues.html#variance
markettor/hogql/database/schema/groups.py:0: note: Consider using "Mapping" instead, which is covariant in the value type
markettor/hogql/database/schema/persons.py:0: error: Incompatible types in assignment (expression has type "Organization | None", variable has type "Organization")  [assignment]
markettor/batch_exports/service.py:0: error: Argument 4 to "backfill_export" has incompatible type "datetime | None"; expected "datetime"  [arg-type]
markettor/models/team/team.py:0: error: Statement is unreachable  [unreachable]
markettor/models/team/team.py:0: error: Statement is unreachable  [unreachable]
markettor/models/hog_functions/hog_function.py:0: error: Argument 1 to "get" of "dict" has incompatible type "str | None"; expected "str"  [arg-type]
markettor/models/user.py:0: error: Incompatible types in assignment (expression has type "type[User]", base class "BaseManager" defined the type as "type[_T]")  [assignment]
markettor/models/user.py:0: error: Cannot override class variable (previously declared on base class "AbstractBaseUser") with instance variable  [misc]
markettor/models/user.py:0: error: Incompatible types in assignment (expression has type "None", base class "AbstractUser" defined the type as "CharField[str | int | Combinable, str]")  [assignment]
markettor/models/user.py:0: error: Cannot override class variable (previously declared on base class "AbstractUser") with instance variable  [misc]
markettor/models/user.py:0: error: Incompatible types in assignment (expression has type "markettor.models.user.UserManager[Any]", base class "AbstractUser" defined the type as "django.contrib.auth.models.UserManager[User]")  [assignment]
markettor/models/user.py:0: error: Cannot override writeable attribute with read-only property  [override]
markettor/models/user.py:0: error: Signature of "is_superuser" incompatible with supertype "PermissionsMixin"  [override]
markettor/models/user.py:0: note: Superclass:
markettor/models/user.py:0: note: BooleanField[bool | Combinable, bool]
markettor/models/user.py:0: note: Subclass:
markettor/models/user.py:0: note: bool
markettor/models/user.py:0: error: "User" has no attribute "social_auth"  [attr-defined]
markettor/models/user.py:0: error: "User" has no attribute "social_auth"  [attr-defined]
markettor/models/plugin.py:0: error: Argument 1 to "extract_plugin_code" has incompatible type "bytes | memoryview | None"; expected "bytes"  [arg-type]
markettor/models/plugin.py:0: error: Name "timezone.datetime" is not defined  [name-defined]
markettor/models/plugin.py:0: error: Name "timezone.datetime" is not defined  [name-defined]
markettor/models/person/person.py:0: error: "_T" has no attribute "_add_distinct_ids"  [attr-defined]
markettor/models/person/person.py:0: error: Argument "version" to "create_person" has incompatible type "int | None"; expected "int"  [arg-type]
markettor/models/person/person.py:0: error: Incompatible types in assignment (expression has type "list[Never]", variable has type "QuerySet[PersonDistinctId, str]")  [assignment]
markettor/models/organization_invite.py:0: error: Argument "level" to "join" of "User" has incompatible type "int"; expected "Level"  [arg-type]
markettor/hogql_queries/legacy_compatibility/filter_to_query.py:0: error: Dict entry 4 has incompatible type "str": "Literal[0, 1, 2, 3, 4] | None"; expected "str": "str | None"  [dict-item]
markettor/hogql_queries/legacy_compatibility/filter_to_query.py:0: error: Item "None" of "Any | None" has no attribute "__iter__" (not iterable)  [union-attr]
markettor/hogql_queries/legacy_compatibility/filter_to_query.py:0: error: Argument 1 to "float" has incompatible type "Any | None"; expected "str | Buffer | SupportsFloat | SupportsIndex"  [arg-type]
markettor/hogql_queries/legacy_compatibility/filter_to_query.py:0: error: Argument 1 to "clean_display" has incompatible type "Any | None"; expected "str"  [arg-type]
markettor/hogql_queries/legacy_compatibility/filter_to_query.py:0: error: Dict entry 0 has incompatible type "str": "FunnelsFilter"; expected "str": "TrendsFilter"  [dict-item]
markettor/hogql_queries/legacy_compatibility/filter_to_query.py:0: error: Dict entry 0 has incompatible type "str": "RetentionFilter"; expected "str": "TrendsFilter"  [dict-item]
markettor/hogql_queries/legacy_compatibility/filter_to_query.py:0: error: Argument 1 to "to_base_entity_dict" has incompatible type "Any | None"; expected "dict[Any, Any]"  [arg-type]
markettor/hogql_queries/legacy_compatibility/filter_to_query.py:0: error: Argument 1 to "to_base_entity_dict" has incompatible type "Any | None"; expected "dict[Any, Any]"  [arg-type]
markettor/hogql_queries/legacy_compatibility/filter_to_query.py:0: error: Dict entry 0 has incompatible type "str": "PathsFilter"; expected "str": "TrendsFilter"  [dict-item]
markettor/hogql_queries/legacy_compatibility/filter_to_query.py:0: error: Dict entry 0 has incompatible type "str": "LifecycleFilter"; expected "str": "TrendsFilter"  [dict-item]
markettor/hogql_queries/legacy_compatibility/filter_to_query.py:0: error: Dict entry 0 has incompatible type "str": "StickinessFilter"; expected "str": "TrendsFilter"  [dict-item]
markettor/session_recordings/models/session_recording.py:0: error: Argument "distinct_id" to "MissingPerson" has incompatible type "str | None"; expected "str"  [arg-type]
markettor/session_recordings/models/session_recording.py:0: error: Incompatible type for lookup 'persondistinctid__team_id': (got "Team", expected "str | int")  [misc]
ee/tasks/subscriptions/slack_subscriptions.py:0: error: Item "None" of "datetime | None" has no attribute "strftime"  [union-attr]
markettor/warehouse/models/table.py:0: error: Item "None" of "DataWarehouseCredential | None" has no attribute "access_key"  [union-attr]
markettor/warehouse/models/table.py:0: error: Item "None" of "DataWarehouseCredential | None" has no attribute "access_secret"  [union-attr]
markettor/warehouse/models/table.py:0: error: Item "None" of "DataWarehouseCredential | None" has no attribute "access_key"  [union-attr]
markettor/warehouse/models/table.py:0: error: Item "None" of "DataWarehouseCredential | None" has no attribute "access_secret"  [union-attr]
markettor/warehouse/models/table.py:0: error: Item "None" of "DataWarehouseCredential | None" has no attribute "access_key"  [union-attr]
markettor/warehouse/models/table.py:0: error: Item "None" of "DataWarehouseCredential | None" has no attribute "access_secret"  [union-attr]
markettor/queries/util.py:0: error: Module has no attribute "utc"  [attr-defined]
markettor/models/cohort/cohort.py:0: error: Need type annotation for "people"  [var-annotated]
markettor/hogql_queries/utils/query_date_range.py:0: error: Item "None" of "dict[str, int] | None" has no attribute "get"  [union-attr]
markettor/hogql_queries/utils/query_date_range.py:0: error: Unsupported operand types for * ("object" and "int")  [operator]
markettor/hogql_queries/utils/query_date_range.py:0: error: Incompatible return value type (got "int", expected "timedelta")  [return-value]
markettor/hogql_queries/utils/query_date_range.py:0: error: Item "None" of "IntervalType | None" has no attribute "name"  [union-attr]
markettor/hogql_queries/utils/query_date_range.py:0: error: Item "None" of "IntervalType | None" has no attribute "name"  [union-attr]
markettor/hogql_queries/utils/query_date_range.py:0: error: Incompatible default for argument "source" (default has type "None", argument has type "Expr")  [assignment]
markettor/hogql_queries/utils/query_date_range.py:0: note: PEP 484 prohibits implicit Optional. Accordingly, mypy has changed its default to no_implicit_optional=True
markettor/hogql_queries/utils/query_date_range.py:0: note: Use https://github.com/hauntsaninja/no_implicit_optional to automatically upgrade your codebase
markettor/hogql_queries/utils/query_date_range.py:0: error: Item "None" of "IntervalType | None" has no attribute "name"  [union-attr]
markettor/hogql/resolver.py:0: error: List comprehension has incompatible type List[SelectQueryType | None]; expected List[SelectQueryType]  [misc]
markettor/hogql/resolver.py:0: error: Need type annotation for "columns_with_visible_alias" (hint: "columns_with_visible_alias: dict[<type>, <type>] = ...")  [var-annotated]
markettor/hogql/resolver.py:0: error: Statement is unreachable  [unreachable]
markettor/hogql/resolver.py:0: error: Incompatible types in assignment (expression has type "Expr", variable has type "SelectQuery | SelectUnionQuery | Field | None")  [assignment]
markettor/hogql/resolver.py:0: error: Item "None" of "Database | None" has no attribute "get_table"  [union-attr]
markettor/hogql/resolver.py:0: error: Incompatible types in assignment (expression has type "TableType", variable has type "LazyTableType")  [assignment]
markettor/hogql/resolver.py:0: error: Argument "table_type" to "TableAliasType" has incompatible type "LazyTableType"; expected "TableType"  [arg-type]
markettor/hogql/resolver.py:0: error: Incompatible types in assignment (expression has type "LazyTableType", variable has type "TableAliasType")  [assignment]
markettor/hogql/resolver.py:0: error: Argument 1 to "clone_expr" has incompatible type "SelectQuery | SelectUnionQuery | Field | None"; expected "Expr"  [arg-type]
markettor/hogql/resolver.py:0: error: Statement is unreachable  [unreachable]
markettor/hogql/resolver.py:0: error: Item "None" of "JoinExpr | None" has no attribute "join_type"  [union-attr]
markettor/hogql/resolver.py:0: error: Argument "select_query_type" to "SelectViewType" has incompatible type "SelectQueryType | None"; expected "SelectQueryType | SelectUnionQueryType"  [arg-type]
markettor/hogql/resolver.py:0: error: Item "None" of "SelectQuery | SelectUnionQuery | Field | None" has no attribute "type"  [union-attr]
markettor/hogql/resolver.py:0: error: Argument "select_query_type" to "SelectQueryAliasType" has incompatible type "Type | Any | None"; expected "SelectQueryType | SelectUnionQueryType"  [arg-type]
markettor/hogql/resolver.py:0: error: Item "None" of "SelectQuery | SelectUnionQuery | Field | None" has no attribute "type"  [union-attr]
markettor/hogql/resolver.py:0: error: Incompatible types in assignment (expression has type "Type | Any | None", variable has type "BaseTableType | SelectUnionQueryType | SelectQueryType | SelectQueryAliasType | SelectViewType | None")  [assignment]
markettor/hogql/resolver.py:0: error: Argument 1 to "append" of "list" has incompatible type "BaseTableType | SelectUnionQueryType | SelectQueryType | SelectQueryAliasType | SelectViewType | None"; expected "SelectQueryType | SelectUnionQueryType"  [arg-type]
markettor/hogql/resolver.py:0: error: Statement is unreachable  [unreachable]
markettor/hogql/resolver.py:0: error: Statement is unreachable  [unreachable]
markettor/hogql/resolver.py:0: error: Item "None" of "Type | None" has no attribute "resolve_constant_type"  [union-attr]
markettor/hogql/resolver.py:0: error: Item "None" of "Type | None" has no attribute "resolve_constant_type"  [union-attr]
markettor/hogql/resolver.py:0: error: Item "None" of "Type | None" has no attribute "resolve_constant_type"  [union-attr]
markettor/models/feature_flag/feature_flag.py:0: error: Need type annotation for "analytics_dashboards"  [var-annotated]
markettor/models/feature_flag/feature_flag.py:0: error: Unsupported right operand type for in ("str | Any | None")  [operator]
markettor/models/feature_flag/feature_flag.py:0: error: Item "None" of "Insight | None" has no attribute "name"  [union-attr]
markettor/models/feature_flag/feature_flag.py:0: error: Incompatible types in assignment (expression has type "User | None", variable has type "User | AnonymousUser")  [assignment]
markettor/hogql_queries/insights/trends/aggregation_operations.py:0: error: List item 1 has incompatible type "str | None"; expected "str"  [list-item]
markettor/hogql_queries/insights/trends/aggregation_operations.py:0: error: Argument "chain" to "Field" has incompatible type "list[str]"; expected "list[str | int]"  [arg-type]
markettor/hogql_queries/insights/trends/aggregation_operations.py:0: note: "List" is invariant -- see https://mypy.readthedocs.io/en/stable/common_issues.html#variance
markettor/hogql_queries/insights/trends/aggregation_operations.py:0: note: Consider using "Sequence" instead, which is covariant
markettor/hogql_queries/insights/trends/aggregation_operations.py:0: error: List item 1 has incompatible type "str | None"; expected "str"  [list-item]
markettor/hogql_queries/insights/trends/aggregation_operations.py:0: error: Argument "chain" to "Field" has incompatible type "list[str | int] | list[str]"; expected "list[str | int]"  [arg-type]
markettor/hogql_queries/insights/trends/aggregation_operations.py:0: error: Item "SelectUnionQuery" of "SelectQuery | SelectUnionQuery" has no attribute "select"  [union-attr]
markettor/hogql_queries/insights/trends/aggregation_operations.py:0: error: Item "SelectUnionQuery" of "SelectQuery | SelectUnionQuery" has no attribute "select"  [union-attr]
markettor/hogql_queries/insights/trends/aggregation_operations.py:0: error: Item "SelectUnionQuery" of "SelectQuery | SelectUnionQuery" has no attribute "group_by"  [union-attr]
markettor/hogql_queries/insights/trends/aggregation_operations.py:0: error: Item "None" of "list[Expr] | None" has no attribute "append"  [union-attr]
markettor/hogql_queries/insights/trends/aggregation_operations.py:0: error: Item "SelectUnionQuery" of "SelectQuery | SelectUnionQuery" has no attribute "select"  [union-attr]
markettor/hogql_queries/insights/trends/aggregation_operations.py:0: error: Item "SelectUnionQuery" of "SelectQuery | SelectUnionQuery" has no attribute "group_by"  [union-attr]
markettor/hogql_queries/insights/trends/aggregation_operations.py:0: error: Item "None" of "list[Expr] | Any | None" has no attribute "append"  [union-attr]
markettor/hogql/transforms/lazy_tables.py:0: error: Incompatible types in assignment (expression has type "dict[Never, Never]", variable has type "list[ConstraintOverride]")  [assignment]
markettor/hogql/transforms/lazy_tables.py:0: error: Non-overlapping equality check (left operand type: "TableType", right operand type: "LazyTableType")  [comparison-overlap]
markettor/hogql/transforms/lazy_tables.py:0: error: Non-overlapping equality check (left operand type: "TableType", right operand type: "LazyTableType")  [comparison-overlap]
markettor/hogql/transforms/lazy_tables.py:0: error: Name "chain" already defined on line 0  [no-redef]
markettor/hogql/transforms/lazy_tables.py:0: error: Subclass of "TableType" and "LazyTableType" cannot exist: would have incompatible method signatures  [unreachable]
markettor/hogql/transforms/lazy_tables.py:0: error: Statement is unreachable  [unreachable]
markettor/hogql/transforms/lazy_tables.py:0: error: Incompatible types in assignment (expression has type "BaseTableType | SelectUnionQueryType | SelectQueryType | SelectQueryAliasType | SelectViewType", variable has type "SelectQueryAliasType | None")  [assignment]
markettor/hogql/transforms/in_cohort.py:0: error: Incompatible default for argument "context" (default has type "None", argument has type "HogQLContext")  [assignment]
markettor/hogql/transforms/in_cohort.py:0: note: PEP 484 prohibits implicit Optional. Accordingly, mypy has changed its default to no_implicit_optional=True
markettor/hogql/transforms/in_cohort.py:0: note: Use https://github.com/hauntsaninja/no_implicit_optional to automatically upgrade your codebase
markettor/hogql/transforms/in_cohort.py:0: error: Incompatible type for lookup 'team_id': (got "int | None", expected "str | int")  [misc]
markettor/hogql/transforms/in_cohort.py:0: error: Incompatible type for lookup 'team_id': (got "int | None", expected "str | int")  [misc]
markettor/hogql/transforms/in_cohort.py:0: error: Incompatible default for argument "context" (default has type "None", argument has type "HogQLContext")  [assignment]
markettor/hogql/transforms/in_cohort.py:0: note: PEP 484 prohibits implicit Optional. Accordingly, mypy has changed its default to no_implicit_optional=True
markettor/hogql/transforms/in_cohort.py:0: note: Use https://github.com/hauntsaninja/no_implicit_optional to automatically upgrade your codebase
markettor/hogql/transforms/in_cohort.py:0: error: Incompatible type for lookup 'team_id': (got "int | None", expected "str | int")  [misc]
markettor/hogql/transforms/in_cohort.py:0: error: Incompatible type for lookup 'team_id': (got "int | None", expected "str | int")  [misc]
markettor/hogql/transforms/in_cohort.py:0: error: Argument "table" to "JoinExpr" has incompatible type "Expr"; expected "SelectQuery | SelectUnionQuery | Field | None"  [arg-type]
markettor/hogql/transforms/in_cohort.py:0: error: List item 0 has incompatible type "SelectQueryType | None"; expected "SelectQueryType"  [list-item]
markettor/hogql/transforms/in_cohort.py:0: error: Item "None" of "JoinConstraint | None" has no attribute "expr"  [union-attr]
markettor/hogql/transforms/in_cohort.py:0: error: Item "Expr" of "Expr | Any" has no attribute "left"  [union-attr]
markettor/hogql/transforms/in_cohort.py:0: error: List item 0 has incompatible type "SelectQueryType | None"; expected "SelectQueryType"  [list-item]
markettor/hogql/transforms/in_cohort.py:0: error: Item "None" of "JoinConstraint | None" has no attribute "expr"  [union-attr]
markettor/hogql/transforms/in_cohort.py:0: error: Item "Expr" of "Expr | Any" has no attribute "right"  [union-attr]
markettor/hogql/transforms/in_cohort.py:0: error: List item 0 has incompatible type "SelectQueryType | None"; expected "SelectQueryType"  [list-item]
markettor/hogql/transforms/in_cohort.py:0: error: List item 0 has incompatible type "SelectQueryType | None"; expected "SelectQueryType"  [list-item]
markettor/hogql/database/database.py:0: error: Argument "week_start_day" to "Database" has incompatible type "int | Any | None"; expected "WeekStartDay | None"  [arg-type]
markettor/hogql/database/database.py:0: error: "FieldOrTable" has no attribute "fields"  [attr-defined]
markettor/warehouse/models/datawarehouse_saved_query.py:0: error: Argument 1 to "create_hogql_database" has incompatible type "int | None"; expected "int"  [arg-type]
markettor/warehouse/models/datawarehouse_saved_query.py:0: error: Incompatible types in assignment (expression has type "Expr", variable has type "SelectQuery | SelectUnionQuery")  [assignment]
markettor/models/feature_flag/flag_matching.py:0: error: Statement is unreachable  [unreachable]
markettor/models/feature_flag/flag_matching.py:0: error: Value expression in dictionary comprehension has incompatible type "int"; expected type "Literal[0, 1, 2, 3, 4]"  [misc]
markettor/models/feature_flag/flag_matching.py:0: error: Value of type variable "_E" of "ExpressionWrapper" cannot be "object"  [type-var]
markettor/models/feature_flag/flag_matching.py:0: error: Value of type variable "_E" of "ExpressionWrapper" cannot be "object"  [type-var]
markettor/models/feature_flag/flag_matching.py:0: error: Argument 1 to "get" of "dict" has incompatible type "str | None"; expected "str"  [arg-type]
markettor/models/feature_flag/flag_matching.py:0: error: Value of type variable "_E" of "ExpressionWrapper" cannot be "object"  [type-var]
markettor/hogql/printer.py:0: error: Argument 1 to "create_hogql_database" has incompatible type "int | None"; expected "int"  [arg-type]
markettor/hogql/printer.py:0: error: List comprehension has incompatible type List[SelectQueryType | None]; expected List[SelectQueryType]  [misc]
markettor/hogql/printer.py:0: error: Argument "stack" to "_Printer" has incompatible type "list[SelectQuery]"; expected "list[AST] | None"  [arg-type]
markettor/hogql/printer.py:0: note: "List" is invariant -- see https://mypy.readthedocs.io/en/stable/common_issues.html#variance
markettor/hogql/printer.py:0: note: Consider using "Sequence" instead, which is covariant
markettor/hogql/printer.py:0: error: Need type annotation for "found_aliases" (hint: "found_aliases: dict[<type>, <type>] = ...")  [var-annotated]
markettor/hogql/printer.py:0: error: Argument 1 to "len" has incompatible type "list[Expr] | None"; expected "Sized"  [arg-type]
markettor/hogql/printer.py:0: error: Item "None" of "list[Expr] | None" has no attribute "__iter__" (not iterable)  [union-attr]
markettor/hogql/printer.py:0: error: Right operand of "and" is never evaluated  [unreachable]
markettor/hogql/printer.py:0: error: Subclass of "TableType" and "LazyTableType" cannot exist: would have incompatible method signatures  [unreachable]
markettor/hogql/printer.py:0: error: Argument 1 to "_print_escaped_string" of "_Printer" has incompatible type "int | float | UUID | date | None"; expected "float | int | str | list[Any] | tuple[Any, ...] | datetime | date"  [arg-type]
markettor/hogql/printer.py:0: error: Argument 1 to "join" of "str" has incompatible type "list[str | int]"; expected "Iterable[str]"  [arg-type]
markettor/hogql/printer.py:0: error: Name "args" already defined on line 0  [no-redef]
markettor/hogql/printer.py:0: error: Argument 1 to "lookup_field_by_name" has incompatible type "SelectQueryType | None"; expected "SelectQueryType"  [arg-type]
markettor/hogql/printer.py:0: error: Item "TableType" of "TableType | TableAliasType" has no attribute "alias"  [union-attr]
markettor/hogql/printer.py:0: error: "FieldOrTable" has no attribute "name"  [attr-defined]
markettor/hogql/printer.py:0: error: "FieldOrTable" has no attribute "name"  [attr-defined]
markettor/hogql/printer.py:0: error: Argument 1 to "_print_identifier" of "_Printer" has incompatible type "str | None"; expected "str"  [arg-type]
markettor/user_permissions.py:0: error: Incompatible return value type (got "int", expected "Level | None")  [return-value]
markettor/user_permissions.py:0: error: Incompatible return value type (got "int", expected "Level | None")  [return-value]
markettor/user_permissions.py:0: error: Incompatible return value type (got "int", expected "RestrictionLevel")  [return-value]
markettor/tasks/update_survey_iteration.py:0: error: Incompatible types in assignment (expression has type "ForeignKey[Any, _ST] | Any", variable has type "FeatureFlag | Combinable | None")  [assignment]
markettor/tasks/update_survey_iteration.py:0: error: Item "None" of "FeatureFlag | None" has no attribute "filters"  [union-attr]
markettor/tasks/update_survey_iteration.py:0: error: Item "None" of "FeatureFlag | None" has no attribute "filters"  [union-attr]
markettor/tasks/update_survey_iteration.py:0: error: Item "None" of "FeatureFlag | None" has no attribute "save"  [union-attr]
markettor/permissions.py:0: error: Argument 2 to "feature_enabled" has incompatible type "str | None"; expected "str"  [arg-type]
markettor/models/event/util.py:0: error: Incompatible types in assignment (expression has type "str", variable has type "datetime")  [assignment]
markettor/models/event/util.py:0: error: Module has no attribute "utc"  [attr-defined]
markettor/event_usage.py:0: error: Argument 1 to "capture" has incompatible type "str | None"; expected "str"  [arg-type]
markettor/event_usage.py:0: error: Argument 1 to "capture" has incompatible type "str | None"; expected "str"  [arg-type]
markettor/event_usage.py:0: error: Argument 1 to "alias" has incompatible type "str | None"; expected "str"  [arg-type]
markettor/event_usage.py:0: error: Argument 1 to "capture" has incompatible type "str | None"; expected "str"  [arg-type]
markettor/event_usage.py:0: error: Argument 1 to "capture" has incompatible type "str | None"; expected "str"  [arg-type]
markettor/event_usage.py:0: error: Argument 1 to "capture" has incompatible type "str | None"; expected "str"  [arg-type]
markettor/event_usage.py:0: error: Argument 1 to "capture" has incompatible type "str | None"; expected "str"  [arg-type]
markettor/event_usage.py:0: error: Argument 1 to "capture" has incompatible type "str | None"; expected "str"  [arg-type]
markettor/event_usage.py:0: error: Argument 1 to "capture" has incompatible type "str | None"; expected "str"  [arg-type]
markettor/event_usage.py:0: error: Argument 1 to "capture" has incompatible type "str | None"; expected "str"  [arg-type]
markettor/event_usage.py:0: error: Argument 1 to "capture" has incompatible type "str | None"; expected "str"  [arg-type]
markettor/event_usage.py:0: error: Argument 1 to "capture" has incompatible type "str | None"; expected "str"  [arg-type]
markettor/demo/matrix/taxonomy_inference.py:0: error: Name "timezone.datetime" is not defined  [name-defined]
markettor/demo/matrix/matrix.py:0: error: Name "timezone.datetime" is not defined  [name-defined]
markettor/demo/matrix/matrix.py:0: error: Name "timezone.datetime" is not defined  [name-defined]
markettor/demo/matrix/matrix.py:0: error: Name "timezone.datetime" is not defined  [name-defined]
markettor/api/shared.py:0: error: Incompatible return value type (got "int | None", expected "Level | None")  [return-value]
ee/billing/quota_limiting.py:0: error: Unsupported target for indexed assignment ("object")  [index]
ee/billing/quota_limiting.py:0: error: "object" has no attribute "get"  [attr-defined]
ee/billing/quota_limiting.py:0: error: Unsupported target for indexed assignment ("object")  [index]
ee/billing/quota_limiting.py:0: error: Unsupported target for indexed assignment ("object")  [index]
markettor/test/base.py:0: error: Module has no attribute "configure"  [attr-defined]
markettor/test/base.py:0: error: Incompatible types in assignment (expression has type "None", variable has type "Organization")  [assignment]
markettor/test/base.py:0: error: Incompatible types in assignment (expression has type "None", variable has type "Project")  [assignment]
markettor/test/base.py:0: error: Incompatible types in assignment (expression has type "None", variable has type "Team")  [assignment]
markettor/test/base.py:0: error: Incompatible types in assignment (expression has type "None", variable has type "User")  [assignment]
markettor/test/base.py:0: error: Incompatible types in assignment (expression has type "None", variable has type "OrganizationMembership")  [assignment]
markettor/test/base.py:0: error: "MemoryLeakTestMixin" has no attribute "assertLessEqual"  [attr-defined]
markettor/test/base.py:0: error: "MemoryLeakTestMixin" has no attribute "assertLessEqual"  [attr-defined]
markettor/test/base.py:0: error: Item "None" of "FrameType | None" has no attribute "f_back"  [union-attr]
markettor/test/base.py:0: error: Item "None" of "FrameType | Any | None" has no attribute "f_locals"  [union-attr]
markettor/test/base.py:0: error: Item "None" of "AppConfig | None" has no attribute "name"  [union-attr]
markettor/test/base.py:0: error: Item "None" of "FrameType | None" has no attribute "f_back"  [union-attr]
markettor/test/base.py:0: error: Item "None" of "FrameType | Any | None" has no attribute "f_locals"  [union-attr]
markettor/test/base.py:0: error: Item "None" of "FrameType | None" has no attribute "f_back"  [union-attr]
markettor/test/base.py:0: error: Item "None" of "FrameType | Any | None" has no attribute "f_locals"  [union-attr]
markettor/tasks/email.py:0: error: Item "None" of "User | None" has no attribute "first_name"  [union-attr]
markettor/tasks/email.py:0: error: Module "django.utils.timezone" does not explicitly export attribute "timedelta"  [attr-defined]
markettor/tasks/email.py:0: error: Argument "email" to "add_recipient" of "EmailMessage" has incompatible type "str | None"; expected "str"  [arg-type]
markettor/tasks/email.py:0: error: Argument 1 to "capture" has incompatible type "str | None"; expected "str"  [arg-type]
markettor/tasks/email.py:0: error: Incompatible types in assignment (expression has type "Team | None", variable has type "Team")  [assignment]
markettor/api/documentation.py:0: error: Signature of "run_validation" incompatible with supertype "Field"  [override]
markettor/api/documentation.py:0: note: Superclass:
markettor/api/documentation.py:0: note: def run_validation(self, data: Any = ...) -> Any
markettor/api/documentation.py:0: note: Subclass:
markettor/api/documentation.py:0: note: def run_validation(self, data: Any) -> Any
ee/tasks/subscriptions/email_subscriptions.py:0: error: Item "None" of "User | None" has no attribute "email"  [union-attr]
ee/tasks/subscriptions/email_subscriptions.py:0: error: Item "None" of "datetime | None" has no attribute "isoformat"  [union-attr]
ee/tasks/subscriptions/email_subscriptions.py:0: error: Item "None" of "datetime | None" has no attribute "strftime"  [union-attr]
ee/tasks/subscriptions/email_subscriptions.py:0: error: Item "None" of "User | None" has no attribute "first_name"  [union-attr]
ee/billing/billing_manager.py:0: error: Module has no attribute "utc"  [attr-defined]
ee/billing/billing_manager.py:0: error: Cannot resolve keyword 'distinct_id' into field. Choices are: explicit_team_membership, id, joined_at, level, organization, organization_id, role_membership, updated_at, user, user_id  [misc]
ee/billing/billing_manager.py:0: error: Cannot resolve keyword 'email' into field. Choices are: explicit_team_membership, id, joined_at, level, organization, organization_id, role_membership, updated_at, user, user_id  [misc]
ee/billing/billing_manager.py:0: error: Incompatible types in assignment (expression has type "object", variable has type "bool | Combinable | None")  [assignment]
markettor/models/property/util.py:0: error: Incompatible type for lookup 'pk': (got "str | int | list[str]", expected "str | int")  [misc]
markettor/models/property/util.py:0: error: Argument 3 to "format_filter_query" has incompatible type "HogQLContext | None"; expected "HogQLContext"  [arg-type]
markettor/models/property/util.py:0: error: Argument 3 to "format_cohort_subquery" has incompatible type "HogQLContext | None"; expected "HogQLContext"  [arg-type]
markettor/models/property/util.py:0: error: Argument 1 to "append" of "list" has incompatible type "str | int"; expected "str"  [arg-type]
markettor/models/property/util.py:0: error: Argument 1 to "append" of "list" has incompatible type "str | int"; expected "str"  [arg-type]
markettor/models/property/util.py:0: error: Argument 1 to "append" of "list" has incompatible type "str | int"; expected "str"  [arg-type]
markettor/api/utils.py:0: error: Incompatible types in assignment (expression has type "type[EventDefinition]", variable has type "type[EnterpriseEventDefinition]")  [assignment]
markettor/api/utils.py:0: error: Argument 1 to "UUID" has incompatible type "int | str"; expected "str | None"  [arg-type]
markettor/queries/trends/util.py:0: error: Argument 1 to "translate_hogql" has incompatible type "str | None"; expected "str"  [arg-type]
markettor/hogql/property.py:0: error: Incompatible type for lookup 'id': (got "str | int | list[str]", expected "str | int")  [misc]
markettor/hogql/property.py:0: error: Incompatible type for lookup 'pk': (got "str | float", expected "str | int")  [misc]
markettor/api/capture.py:0: error: Module has no attribute "utc"  [attr-defined]
markettor/hogql/filters.py:0: error: Incompatible default for argument "team" (default has type "None", argument has type "Team")  [assignment]
markettor/hogql/filters.py:0: note: PEP 484 prohibits implicit Optional. Accordingly, mypy has changed its default to no_implicit_optional=True
markettor/hogql/filters.py:0: note: Use https://github.com/hauntsaninja/no_implicit_optional to automatically upgrade your codebase
markettor/api/organization.py:0: error: Incompatible return value type (got "int | None", expected "Level | None")  [return-value]
markettor/hogql/query.py:0: error: Incompatible types in assignment (expression has type "None", variable has type "str | SelectQuery | SelectUnionQuery")  [assignment]
markettor/hogql/query.py:0: error: Incompatible types in assignment (expression has type "Expr", variable has type "SelectQuery | SelectUnionQuery")  [assignment]
markettor/hogql/query.py:0: error: Argument 1 to "get_default_limit_for_context" has incompatible type "LimitContext | None"; expected "LimitContext"  [arg-type]
markettor/hogql/query.py:0: error: "SelectQuery" has no attribute "select_queries"  [attr-defined]
markettor/hogql/query.py:0: error: Subclass of "SelectQuery" and "SelectUnionQuery" cannot exist: would have incompatible method signatures  [unreachable]
markettor/api/action.py:0: error: Argument 1 to <tuple> has incompatible type "*tuple[str, ...]"; expected "type[BaseRenderer]"  [arg-type]
markettor/queries/person_query.py:0: error: Incompatible type for lookup 'pk': (got "str | int | list[str]", expected "str | int")  [misc]
markettor/queries/event_query/event_query.py:0: error: Incompatible type for lookup 'pk': (got "str | int | list[str]", expected "str | int")  [misc]
markettor/hogql_queries/sessions_timeline_query_runner.py:0: error: Statement is unreachable  [unreachable]
markettor/hogql_queries/hogql_query_runner.py:0: error: Statement is unreachable  [unreachable]
markettor/hogql_queries/hogql_query_runner.py:0: error: Incompatible return value type (got "SelectQuery | SelectUnionQuery", expected "SelectQuery")  [return-value]
markettor/hogql_queries/events_query_runner.py:0: error: Statement is unreachable  [unreachable]
markettor/queries/breakdown_props.py:0: error: Argument 1 to "translate_hogql" has incompatible type "str | int"; expected "str"  [arg-type]
markettor/queries/breakdown_props.py:0: error: Incompatible type for lookup 'pk': (got "str | None", expected "str | int")  [misc]
markettor/queries/breakdown_props.py:0: error: Incompatible return value type (got "str | None", expected "str")  [return-value]
markettor/queries/actor_base_query.py:0: error: Incompatible types (expression has type "datetime", TypedDict item "created_at" has type "str | None")  [typeddict-item]
markettor/queries/actor_base_query.py:0: error: Incompatible types (expression has type "datetime", TypedDict item "created_at" has type "str | None")  [typeddict-item]
markettor/hogql_queries/insights/funnels/base.py:0: error: Incompatible type for lookup 'pk': (got "str | int | None", expected "str | int")  [misc]
markettor/queries/foss_cohort_query.py:0: error: Incompatible type for lookup 'pk': (got "str | int | list[str]", expected "str | int")  [misc]
markettor/queries/funnels/base.py:0: error: Incompatible types in assignment (expression has type "int | str | None", variable has type "str | None")  [assignment]
markettor/queries/funnels/base.py:0: error: Unsupported right operand type for in ("object")  [operator]
markettor/queries/funnels/base.py:0: error: "object" has no attribute "append"  [attr-defined]
markettor/queries/funnels/base.py:0: error: Unsupported right operand type for in ("object")  [operator]
markettor/queries/funnels/base.py:0: error: "object" has no attribute "append"  [attr-defined]
markettor/queries/funnels/base.py:0: error: Argument 1 to "translate_hogql" has incompatible type "str | int"; expected "str"  [arg-type]
markettor/queries/trends/trends_actors.py:0: error: Incompatible type for lookup 'pk': (got "str | None", expected "str | int")  [misc]
markettor/queries/paths/paths_actors.py:0: error: Incompatible types in assignment (expression has type "str", target has type "int | list[str] | None")  [assignment]
markettor/queries/paths/paths_actors.py:0: error: Incompatible types in assignment (expression has type "str", target has type "int | list[str] | None")  [assignment]
markettor/queries/paths/paths_actors.py:0: error: Incompatible types in assignment (expression has type "str", target has type "int | list[str] | None")  [assignment]
ee/clickhouse/queries/funnels/funnel_correlation.py:0: error: Statement is unreachable  [unreachable]
markettor/api/insight.py:0: error: Argument 1 to <tuple> has incompatible type "*tuple[str, ...]"; expected "type[BaseRenderer]"  [arg-type]
markettor/api/dashboards/dashboard.py:0: error: Argument 1 to "dashboard_queryset" of "DashboardTile" has incompatible type "DashboardTile_RelatedManager"; expected "QuerySet[Any, Any]"  [arg-type]
markettor/api/person.py:0: error: Argument 1 to <tuple> has incompatible type "*tuple[str, ...]"; expected "type[BaseRenderer]"  [arg-type]
markettor/api/person.py:0: error: Argument 1 to "loads" has incompatible type "str | None"; expected "str | bytes | bytearray"  [arg-type]
markettor/api/person.py:0: error: Argument "user" to "log_activity" has incompatible type "User | AnonymousUser"; expected "User | None"  [arg-type]
markettor/api/person.py:0: error: Argument "user" to "log_activity" has incompatible type "User | AnonymousUser"; expected "User | None"  [arg-type]
markettor/api/person.py:0: error: Cannot determine type of "group_properties_filter_group"  [has-type]
markettor/caching/insight_caching_state.py:0: error: Argument "params" to "execute" of "CursorWrapper" has incompatible type "list[object]"; expected "Sequence[bool | int | float | Decimal | str | <6 more items> | None] | Mapping[str, bool | int | float | Decimal | str | <6 more items> | None] | None"  [arg-type]
markettor/api/cohort.py:0: error: Incompatible type for lookup 'pk': (got "str | int | list[str]", expected "str | int")  [misc]
markettor/api/cohort.py:0: error: Incompatible type for lookup 'pk': (got "str | int | list[str]", expected "str | int")  [misc]
markettor/caching/insights_api.py:0: error: Unsupported operand types for >= ("datetime" and "None")  [operator]
markettor/caching/insights_api.py:0: note: Right operand is of type "datetime | None"
markettor/api/feature_flag.py:0: error: Item "Sequence[Any]" of "Any | Sequence[Any] | None" has no attribute "filters"  [union-attr]
markettor/api/feature_flag.py:0: error: Item "None" of "Any | Sequence[Any] | None" has no attribute "filters"  [union-attr]
markettor/api/feature_flag.py:0: error: Incompatible type for lookup 'pk': (got "str | int | list[str]", expected "str | int")  [misc]
markettor/api/feature_flag.py:0: error: Argument 2 to "get_all_feature_flags" has incompatible type "str | None"; expected "str"  [arg-type]
markettor/hogql_queries/web_analytics/web_analytics_query_runner.py:0: error: Module "django.utils.timezone" does not explicitly export attribute "datetime"  [attr-defined]
markettor/hogql_queries/web_analytics/web_analytics_query_runner.py:0: error: Argument 1 to "append" of "list" has incompatible type "EventPropertyFilter"; expected "Expr"  [arg-type]
markettor/hogql_queries/insights/trends/trends_query_runner.py:0: error: Module "django.utils.timezone" does not explicitly export attribute "datetime"  [attr-defined]
markettor/hogql_queries/insights/trends/trends_query_runner.py:0: error: Statement is unreachable  [unreachable]
markettor/hogql_queries/insights/stickiness_query_runner.py:0: error: Module "django.utils.timezone" does not explicitly export attribute "datetime"  [attr-defined]
markettor/hogql_queries/insights/retention_query_runner.py:0: error: Item "None" of "JoinExpr | None" has no attribute "sample"  [union-attr]
markettor/hogql_queries/insights/retention_query_runner.py:0: error: Unsupported operand types for - ("int" and "None")  [operator]
markettor/hogql_queries/insights/retention_query_runner.py:0: note: Right operand is of type "int | None"
markettor/hogql_queries/insights/retention_query_runner.py:0: error: Item "SelectUnionQuery" of "SelectQuery | SelectUnionQuery" has no attribute "select"  [union-attr]
markettor/hogql_queries/insights/retention_query_runner.py:0: error: Incompatible return value type (got "SelectQuery | SelectUnionQuery", expected "SelectQuery")  [return-value]
markettor/hogql_queries/insights/lifecycle_query_runner.py:0: error: Module "django.utils.timezone" does not explicitly export attribute "datetime"  [attr-defined]
markettor/hogql_queries/insights/lifecycle_query_runner.py:0: error: Incompatible types in assignment (expression has type "Expr", variable has type "Constant")  [assignment]
markettor/hogql_queries/insights/lifecycle_query_runner.py:0: error: Incompatible types in assignment (expression has type "Expr", variable has type "Constant")  [assignment]
markettor/hogql_queries/insights/lifecycle_query_runner.py:0: error: Argument "exprs" to "And" has incompatible type "list[CompareOperation]"; expected "list[Expr]"  [arg-type]
markettor/hogql_queries/insights/lifecycle_query_runner.py:0: note: "List" is invariant -- see https://mypy.readthedocs.io/en/stable/common_issues.html#variance
markettor/hogql_queries/insights/lifecycle_query_runner.py:0: note: Consider using "Sequence" instead, which is covariant
markettor/hogql_queries/insights/lifecycle_query_runner.py:0: error: Item "SelectUnionQuery" of "SelectQuery | SelectUnionQuery" has no attribute "select_from"  [union-attr]
markettor/hogql_queries/insights/lifecycle_query_runner.py:0: error: Item "None" of "JoinExpr | Any | None" has no attribute "sample"  [union-attr]
markettor/hogql_queries/insights/funnels/funnels_query_runner.py:0: error: Module "django.utils.timezone" does not explicitly export attribute "datetime"  [attr-defined]
markettor/api/survey.py:0: error: Incompatible types in assignment (expression has type "Any | Sequence[Any] | None", variable has type "Survey | None")  [assignment]
markettor/api/survey.py:0: error: Item "list[_ErrorFullDetails]" of "_FullDetailDict | list[_ErrorFullDetails] | dict[str, _ErrorFullDetails]" has no attribute "get"  [union-attr]
markettor/api/survey.py:0: error: Item "object" of "object | Any" has no attribute "__iter__" (not iterable)  [union-attr]
markettor/hogql_queries/web_analytics/web_overview.py:0: error: Module "django.utils.timezone" does not explicitly export attribute "datetime"  [attr-defined]
markettor/hogql_queries/web_analytics/top_clicks.py:0: error: Module "django.utils.timezone" does not explicitly export attribute "datetime"  [attr-defined]
markettor/api/user.py:0: error: Module has no attribute "utc"  [attr-defined]
markettor/api/user.py:0: error: Module has no attribute "utc"  [attr-defined]
markettor/api/user.py:0: error: "User" has no attribute "social_auth"  [attr-defined]
ee/clickhouse/queries/related_actors_query.py:0: error: Argument 1 to "_query_related_groups" of "RelatedActorsQuery" has incompatible type "int"; expected "Literal[0, 1, 2, 3, 4]"  [arg-type]
ee/api/test/base.py:0: error: Incompatible types in assignment (expression has type "None", variable has type "License")  [assignment]
ee/api/test/base.py:0: error: "setUpTestData" undefined in superclass  [misc]
markettor/warehouse/external_data_source/jobs.py:0: error: Incompatible type for lookup 'id': (got "UUID | None", expected "UUID | str")  [misc]
markettor/warehouse/api/test/test_table.py:0: error: Item "None" of "DataWarehouseCredential | None" has no attribute "access_key"  [union-attr]
markettor/warehouse/api/test/test_table.py:0: error: Item "None" of "DataWarehouseCredential | None" has no attribute "access_secret"  [union-attr]
markettor/warehouse/api/test/test_table.py:0: error: Item "None" of "DataWarehouseCredential | None" has no attribute "access_key"  [union-attr]
markettor/warehouse/api/test/test_table.py:0: error: Item "None" of "DataWarehouseCredential | None" has no attribute "access_secret"  [union-attr]
markettor/test/test_utils.py:0: error: Argument 5 to "post" of "_RequestFactory" has incompatible type "**dict[str, str]"; expected "Mapping[str, Any] | None"  [arg-type]
markettor/test/test_plugin_log_entry.py:0: error: Module "django.utils.timezone" does not explicitly export attribute "datetime"  [attr-defined]
markettor/test/test_plugin_log_entry.py:0: error: Module "django.utils.timezone" does not explicitly export attribute "timedelta"  [attr-defined]
markettor/test/test_health.py:0: error: "HttpResponse" has no attribute "json"  [attr-defined]
markettor/test/test_health.py:0: error: "HttpResponse" has no attribute "json"  [attr-defined]
markettor/test/test_health.py:0: error: "HttpResponse" has no attribute "json"  [attr-defined]
markettor/test/test_health.py:0: error: "HttpResponse" has no attribute "json"  [attr-defined]
markettor/test/test_health.py:0: error: "HttpResponse" has no attribute "json"  [attr-defined]
markettor/test/test_health.py:0: error: Incompatible return value type (got "_MonkeyPatchedWSGIResponse", expected "HttpResponse")  [return-value]
markettor/test/test_health.py:0: error: Incompatible return value type (got "_MonkeyPatchedWSGIResponse", expected "HttpResponse")  [return-value]
markettor/test/test_feature_flag_analytics.py:0: error: Item "None" of "Dashboard | None" has no attribute "name"  [union-attr]
markettor/test/test_feature_flag_analytics.py:0: error: Item "None" of "Dashboard | None" has no attribute "name"  [union-attr]
markettor/test/test_feature_flag_analytics.py:0: error: Item "None" of "Dashboard | None" has no attribute "tiles"  [union-attr]
markettor/test/test_feature_flag_analytics.py:0: error: Item "None" of "Dashboard | None" has no attribute "tiles"  [union-attr]
markettor/test/test_feature_flag_analytics.py:0: error: Item "None" of "Dashboard | None" has no attribute "delete"  [union-attr]
markettor/temporal/data_imports/pipelines/sql_database/helpers.py:0: error: Unused "type: ignore" comment  [unused-ignore]
markettor/tasks/test/test_update_survey_iteration.py:0: error: Item "None" of "FeatureFlag | None" has no attribute "filters"  [union-attr]
markettor/tasks/test/test_stop_surveys_reached_target.py:0: error: No overload variant of "__sub__" of "datetime" matches argument type "None"  [operator]
markettor/tasks/test/test_stop_surveys_reached_target.py:0: note: Possible overload variants:
markettor/tasks/test/test_stop_surveys_reached_target.py:0: note: def __sub__(self, datetime, /) -> timedelta
markettor/tasks/test/test_stop_surveys_reached_target.py:0: note: def __sub__(self, timedelta, /) -> datetime
markettor/tasks/test/test_stop_surveys_reached_target.py:0: note: Right operand is of type "datetime | None"
markettor/tasks/test/test_stop_surveys_reached_target.py:0: error: No overload variant of "__sub__" of "datetime" matches argument type "None"  [operator]
markettor/tasks/test/test_stop_surveys_reached_target.py:0: note: Possible overload variants:
markettor/tasks/test/test_stop_surveys_reached_target.py:0: note: def __sub__(self, datetime, /) -> timedelta
markettor/tasks/test/test_stop_surveys_reached_target.py:0: note: def __sub__(self, timedelta, /) -> datetime
markettor/tasks/test/test_stop_surveys_reached_target.py:0: note: Right operand is of type "datetime | None"
markettor/tasks/exports/test/test_image_exporter.py:0: error: Function is missing a type annotation  [no-untyped-def]
markettor/tasks/exports/test/test_image_exporter.py:0: error: Function is missing a type annotation  [no-untyped-def]
markettor/tasks/exports/test/test_image_exporter.py:0: error: Function is missing a type annotation for one or more arguments  [no-untyped-def]
markettor/tasks/exports/test/test_image_exporter.py:0: error: Function is missing a type annotation for one or more arguments  [no-untyped-def]
markettor/tasks/exports/test/test_image_exporter.py:0: error: Function is missing a type annotation for one or more arguments  [no-untyped-def]
markettor/tasks/exports/test/test_export_utils.py:0: error: Function is missing a type annotation  [no-untyped-def]
markettor/tasks/exports/test/test_export_utils.py:0: error: Function is missing a type annotation  [no-untyped-def]
markettor/tasks/exports/test/test_export_utils.py:0: error: Function is missing a type annotation  [no-untyped-def]
markettor/tasks/exports/test/test_csv_exporter_url_sanitising.py:0: error: Function is missing a type annotation for one or more arguments  [no-untyped-def]
markettor/tasks/exports/test/test_csv_exporter_url_sanitising.py:0: error: Function is missing a type annotation for one or more arguments  [no-untyped-def]
markettor/tasks/exports/test/test_csv_exporter_renders.py:0: error: Function is missing a type annotation  [no-untyped-def]
markettor/tasks/exports/test/test_csv_exporter_renders.py:0: error: Item "memoryview" of "bytes | memoryview | None" has no attribute "decode"  [union-attr]
markettor/tasks/exports/test/test_csv_exporter_renders.py:0: error: Item "None" of "bytes | memoryview | None" has no attribute "decode"  [union-attr]
markettor/tasks/exports/test/test_csv_exporter_renders.py:0: error: Item "memoryview" of "bytes | memoryview | None" has no attribute "decode"  [union-attr]
markettor/tasks/exports/test/test_csv_exporter_renders.py:0: error: Item "None" of "bytes | memoryview | None" has no attribute "decode"  [union-attr]
markettor/hogql_queries/test/test_query_runner.py:0: error: Variable "TestQueryRunner" is not valid as a type  [valid-type]
markettor/hogql_queries/test/test_query_runner.py:0: note: See https://mypy.readthedocs.io/en/stable/common_issues.html#variables-vs-type-aliases
markettor/hogql_queries/test/test_query_runner.py:0: error: Invalid base class "TestQueryRunner"  [misc]
markettor/hogql_queries/test/test_hogql_query_runner.py:0: error: Incompatible types in assignment (expression has type "Expr", variable has type "SelectQuery")  [assignment]
markettor/hogql_queries/test/test_hogql_query_runner.py:0: error: Incompatible types in assignment (expression has type "Expr", variable has type "SelectQuery")  [assignment]
markettor/hogql_queries/test/test_hogql_query_runner.py:0: error: Incompatible types in assignment (expression has type "Expr", variable has type "SelectQuery")  [assignment]
markettor/hogql_queries/legacy_compatibility/test/test_filter_to_query.py:0: error: Need type annotation for "properties_0" (hint: "properties_0: list[<type>] = ...")  [var-annotated]
markettor/hogql_queries/legacy_compatibility/test/test_filter_to_query.py:0: error: Need type annotation for "properties_3" (hint: "properties_3: dict[<type>, <type>] = ...")  [var-annotated]
markettor/hogql_queries/legacy_compatibility/test/test_filter_to_query.py:0: error: Need type annotation for "filter" (hint: "filter: dict[<type>, <type>] = ...")  [var-annotated]
markettor/hogql_queries/legacy_compatibility/test/test_filter_to_query.py:0: error: Need type annotation for "filter" (hint: "filter: dict[<type>, <type>] = ...")  [var-annotated]
markettor/hogql_queries/legacy_compatibility/test/test_filter_to_query.py:0: error: Need type annotation for "filter" (hint: "filter: dict[<type>, <type>] = ...")  [var-annotated]
markettor/hogql_queries/insights/test/test_paginators.py:0: error: Value of type "object" is not indexable  [index]
markettor/hogql_queries/insights/test/test_paginators.py:0: error: Value of type "object" is not indexable  [index]
markettor/hogql_queries/insights/test/test_paginators.py:0: error: Value of type "object" is not indexable  [index]
markettor/hogql/test/test_timings.py:0: error: No overload variant of "__setitem__" of "list" matches argument types "int", "float"  [call-overload]
markettor/hogql/test/test_timings.py:0: note: Possible overload variants:
markettor/hogql/test/test_timings.py:0: note: def __setitem__(self, SupportsIndex, int, /) -> None
markettor/hogql/test/test_timings.py:0: note: def __setitem__(self, slice, Iterable[int], /) -> None
markettor/hogql/test/test_property.py:0: error: Argument 1 to "_property_to_expr" of "TestProperty" has incompatible type "HogQLPropertyFilter"; expected "PropertyGroup | Property | dict[Any, Any] | list[Any]"  [arg-type]
markettor/hogql/test/test_printer.py:0: error: Argument 2 to "Database" has incompatible type "int"; expected "WeekStartDay | None"  [arg-type]
markettor/hogql/test/test_printer.py:0: error: Argument 2 to "Database" has incompatible type "int"; expected "WeekStartDay | None"  [arg-type]
markettor/hogql/test/test_printer.py:0: error: Item "SelectUnionQuery" of "SelectQuery | SelectUnionQuery" has no attribute "settings"  [union-attr]
markettor/hogql/test/test_printer.py:0: error: Item "SelectUnionQuery" of "SelectQuery | SelectUnionQuery" has no attribute "settings"  [union-attr]
markettor/hogql/test/test_printer.py:0: error: "TestPrinter" has no attribute "snapshot"  [attr-defined]
markettor/hogql/test/test_modifiers.py:0: error: Unsupported right operand type for in ("str | None")  [operator]
markettor/hogql/test/test_modifiers.py:0: error: Unsupported right operand type for in ("str | None")  [operator]
markettor/hogql/test/test_modifiers.py:0: error: Unsupported right operand type for in ("str | None")  [operator]
markettor/hogql/test/test_modifiers.py:0: error: Unsupported right operand type for in ("str | None")  [operator]
markettor/hogql/test/test_modifiers.py:0: error: Unsupported right operand type for in ("str | None")  [operator]
markettor/hogql/test/test_modifiers.py:0: error: Unsupported right operand type for in ("str | None")  [operator]
markettor/hogql/test/test_modifiers.py:0: error: Unsupported right operand type for in ("str | None")  [operator]
markettor/hogql/test/test_modifiers.py:0: error: Unsupported right operand type for in ("str | None")  [operator]
markettor/hogql/test/test_modifiers.py:0: error: Unsupported right operand type for in ("str | None")  [operator]
markettor/hogql/test/test_modifiers.py:0: error: Unsupported right operand type for in ("str | None")  [operator]
markettor/hogql/test/test_modifiers.py:0: error: Unsupported right operand type for in ("str | None")  [operator]
markettor/hogql/test/test_modifiers.py:0: error: Unsupported right operand type for in ("str | None")  [operator]
markettor/hogql/test/test_modifiers.py:0: error: Unsupported right operand type for in ("str | None")  [operator]
markettor/hogql/test/_test_parser.py:0: error: Invalid base class  [misc]
markettor/hogql/test/_test_parser.py:0: error: Argument "table" to "JoinExpr" has incompatible type "Placeholder"; expected "SelectQuery | SelectUnionQuery | Field | None"  [arg-type]
markettor/hogql/test/_test_parser.py:0: error: Item "None" of "JoinExpr | None" has no attribute "table"  [union-attr]
markettor/hogql/test/_test_parser.py:0: error: Item "None" of "JoinExpr | None" has no attribute "table"  [union-attr]
markettor/hogql/test/_test_parser.py:0: error: Item "None" of "JoinExpr | None" has no attribute "table"  [union-attr]
markettor/hogql/test/_test_parser.py:0: error: Item "None" of "JoinExpr | None" has no attribute "table"  [union-attr]
markettor/hogql/test/_test_parser.py:0: error: Item "None" of "JoinExpr | None" has no attribute "table"  [union-attr]
markettor/hogql/test/_test_parser.py:0: error: Item "None" of "JoinExpr | None" has no attribute "alias"  [union-attr]
markettor/hogql/test/_test_parser.py:0: error: Item "None" of "JoinExpr | None" has no attribute "table"  [union-attr]
markettor/hogql/database/schema/event_sessions.py:0: error: Statement is unreachable  [unreachable]
markettor/hogql/ai.py:0: error: No overload variant of "__getitem__" of "tuple" matches argument type "str"  [call-overload]
markettor/hogql/ai.py:0: note: Possible overload variants:
markettor/hogql/ai.py:0: note: def __getitem__(self, SupportsIndex, /) -> str | Any
markettor/hogql/ai.py:0: note: def __getitem__(self, slice, /) -> tuple[str | Any, ...]
markettor/heatmaps/test/test_heatmaps_api.py:0: error: "HttpResponse" has no attribute "json"  [attr-defined]
markettor/heatmaps/test/test_heatmaps_api.py:0: error: "HttpResponse" has no attribute "json"  [attr-defined]
markettor/heatmaps/test/test_heatmaps_api.py:0: error: "HttpResponse" has no attribute "json"  [attr-defined]
markettor/heatmaps/test/test_heatmaps_api.py:0: error: "HttpResponse" has no attribute "json"  [attr-defined]
markettor/heatmaps/test/test_heatmaps_api.py:0: error: "HttpResponse" has no attribute "json"  [attr-defined]
markettor/heatmaps/test/test_heatmaps_api.py:0: error: "HttpResponse" has no attribute "json"  [attr-defined]
markettor/api/uploaded_media.py:0: error: Argument 1 to "read_bytes" has incompatible type "str | None"; expected "str"  [arg-type]
markettor/api/uploaded_media.py:0: error: Argument 1 to "read_bytes" has incompatible type "str | None"; expected "str"  [arg-type]
markettor/api/test/test_utils.py:0: error: Incompatible types in assignment (expression has type "dict[str, str]", variable has type "QueryDict")  [assignment]
markettor/api/test/test_survey.py:0: error: Item "None" of "FeatureFlag | None" has no attribute "active"  [union-attr]
markettor/api/test/test_stickiness.py:0: error: Module has no attribute "utc"  [attr-defined]
markettor/api/test/test_stickiness.py:0: error: Module has no attribute "utc"  [attr-defined]
markettor/api/test/test_stickiness.py:0: error: Module has no attribute "utc"  [attr-defined]
markettor/api/test/test_stickiness.py:0: error: Module has no attribute "utc"  [attr-defined]
markettor/api/test/test_stickiness.py:0: error: Module has no attribute "utc"  [attr-defined]
markettor/api/test/test_stickiness.py:0: error: Module has no attribute "utc"  [attr-defined]
markettor/api/test/test_stickiness.py:0: error: Module has no attribute "utc"  [attr-defined]
markettor/api/test/test_stickiness.py:0: error: Module has no attribute "utc"  [attr-defined]
markettor/api/test/test_stickiness.py:0: error: Module has no attribute "utc"  [attr-defined]
markettor/api/test/test_signup.py:0: error: Module "django.utils.timezone" does not explicitly export attribute "datetime"  [attr-defined]
markettor/api/test/test_signup.py:0: error: Module "django.utils.timezone" does not explicitly export attribute "datetime"  [attr-defined]
markettor/api/test/test_signup.py:0: error: Module "django.utils.timezone" does not explicitly export attribute "datetime"  [attr-defined]
markettor/api/test/test_signup.py:0: error: Module "django.utils.timezone" does not explicitly export attribute "datetime"  [attr-defined]
markettor/api/test/test_preflight.py:0: error: Module "django.utils.timezone" does not explicitly export attribute "datetime"  [attr-defined]
markettor/api/test/test_preflight.py:0: error: Module "django.utils.timezone" does not explicitly export attribute "datetime"  [attr-defined]
markettor/api/test/test_personal_api_keys.py:0: error: Item "None" of "str | None" has no attribute "startswith"  [union-attr]
markettor/api/test/test_personal_api_keys.py:0: error: Item "None" of "str | None" has no attribute "startswith"  [union-attr]
markettor/api/test/test_person.py:0: error: Argument "data" to "get" of "APIClient" has incompatible type "dict[str, object]"; expected "Mapping[str, str | bytes | int | Iterable[str | bytes | int]] | Iterable[tuple[str, str | bytes | int | Iterable[str | bytes | int]]] | None"  [arg-type]
markettor/api/test/test_organization_domain.py:0: error: Item "None" of "datetime | None" has no attribute "strftime"  [union-attr]
markettor/api/signup.py:0: error: Argument 1 to "create_user" of "UserManager" has incompatible type "str | None"; expected "str"  [arg-type]
markettor/api/organization_member.py:0: error: "User" has no attribute "totpdevice_set"  [attr-defined]
markettor/api/organization_member.py:0: error: "User" has no attribute "social_auth"  [attr-defined]
markettor/api/organization_member.py:0: error: Signature of "update" incompatible with supertype "ModelSerializer"  [override]
markettor/api/organization_member.py:0: note: Superclass:
markettor/api/organization_member.py:0: note: def update(self, instance: Any, validated_data: Any) -> Any
markettor/api/organization_member.py:0: note: Subclass:
markettor/api/organization_member.py:0: note: def update(self, updated_membership: Any, validated_data: Any, **kwargs: Any) -> Any
markettor/api/organization_member.py:0: error: Signature of "update" incompatible with supertype "BaseSerializer"  [override]
markettor/api/organization_member.py:0: note: Superclass:
markettor/api/organization_member.py:0: note: def update(self, instance: Any, validated_data: Any) -> Any
markettor/api/organization_member.py:0: note: Subclass:
markettor/api/organization_member.py:0: note: def update(self, updated_membership: Any, validated_data: Any, **kwargs: Any) -> Any
markettor/api/organization_feature_flag.py:0: error: Invalid index type "str | None" for "dict[str, int]"; expected type "str"  [index]
markettor/api/organization_feature_flag.py:0: error: Invalid index type "str | None" for "dict[str, int]"; expected type "str"  [index]
markettor/api/organization_feature_flag.py:0: error: Invalid index type "str | None" for "dict[str, int]"; expected type "str"  [index]
markettor/api/notebook.py:0: error: Incompatible types in assignment (expression has type "int", variable has type "str | None")  [assignment]
markettor/warehouse/data_load/validate_schema.py:0: error: Incompatible types in assignment (expression has type "object", variable has type "DataWarehouseCredential | Combinable | None")  [assignment]
markettor/warehouse/data_load/validate_schema.py:0: error: Incompatible types in assignment (expression has type "object", variable has type "str | int | Combinable")  [assignment]
markettor/warehouse/data_load/validate_schema.py:0: error: Incompatible types in assignment (expression has type "dict[str, dict[str, str | bool]] | dict[str, str]", variable has type "dict[str, dict[str, str]]")  [assignment]
markettor/warehouse/data_load/source_templates.py:0: error: Incompatible types in assignment (expression has type "str", variable has type "Type")  [assignment]
markettor/tasks/exports/test/test_csv_exporter.py:0: error: Function is missing a return type annotation  [no-untyped-def]
markettor/tasks/exports/test/test_csv_exporter.py:0: error: Function is missing a type annotation  [no-untyped-def]
markettor/tasks/exports/test/test_csv_exporter.py:0: error: Function is missing a type annotation for one or more arguments  [no-untyped-def]
markettor/tasks/exports/test/test_csv_exporter.py:0: error: Function is missing a type annotation for one or more arguments  [no-untyped-def]
markettor/tasks/exports/test/test_csv_exporter.py:0: error: Function is missing a type annotation for one or more arguments  [no-untyped-def]
markettor/tasks/exports/test/test_csv_exporter.py:0: error: Function is missing a type annotation for one or more arguments  [no-untyped-def]
markettor/tasks/exports/test/test_csv_exporter.py:0: error: Function is missing a type annotation for one or more arguments  [no-untyped-def]
markettor/tasks/exports/test/test_csv_exporter.py:0: error: Function is missing a type annotation for one or more arguments  [no-untyped-def]
markettor/tasks/exports/test/test_csv_exporter.py:0: error: Function is missing a type annotation for one or more arguments  [no-untyped-def]
markettor/tasks/exports/test/test_csv_exporter.py:0: error: Argument 1 to "BytesIO" has incompatible type "bytes | memoryview | None"; expected "Buffer"  [arg-type]
markettor/tasks/exports/test/test_csv_exporter.py:0: error: Function is missing a type annotation for one or more arguments  [no-untyped-def]
markettor/tasks/exports/test/test_csv_exporter.py:0: error: Function is missing a type annotation for one or more arguments  [no-untyped-def]
markettor/tasks/exports/test/test_csv_exporter.py:0: error: Function is missing a type annotation for one or more arguments  [no-untyped-def]
markettor/tasks/exports/test/test_csv_exporter.py:0: error: Function is missing a type annotation for one or more arguments  [no-untyped-def]
markettor/tasks/exports/test/test_csv_exporter.py:0: error: Argument 1 to "read" has incompatible type "str | None"; expected "str"  [arg-type]
markettor/tasks/exports/test/test_csv_exporter.py:0: error: Argument 1 to "read" has incompatible type "str | None"; expected "str"  [arg-type]
markettor/tasks/exports/test/test_csv_exporter.py:0: error: Argument 1 to "read" has incompatible type "str | None"; expected "str"  [arg-type]
markettor/tasks/exports/test/test_csv_exporter.py:0: error: Argument 1 to "read" has incompatible type "str | None"; expected "str"  [arg-type]
markettor/tasks/exports/test/test_csv_exporter.py:0: error: Argument 1 to "read" has incompatible type "str | None"; expected "str"  [arg-type]
markettor/queries/trends/test/test_person.py:0: error: "str" has no attribute "get"  [attr-defined]
markettor/queries/trends/test/test_person.py:0: error: Invalid index type "int" for "_MonkeyPatchedResponse"; expected type "str"  [index]
markettor/queries/trends/test/test_person.py:0: error: "str" has no attribute "get"  [attr-defined]
markettor/queries/trends/test/test_person.py:0: error: Invalid index type "int" for "_MonkeyPatchedResponse"; expected type "str"  [index]
markettor/queries/trends/test/test_person.py:0: error: "str" has no attribute "get"  [attr-defined]
markettor/queries/trends/test/test_person.py:0: error: Invalid index type "int" for "_MonkeyPatchedResponse"; expected type "str"  [index]
markettor/queries/trends/test/test_person.py:0: error: "str" has no attribute "get"  [attr-defined]
markettor/queries/trends/test/test_person.py:0: error: Invalid index type "int" for "_MonkeyPatchedResponse"; expected type "str"  [index]
markettor/queries/trends/test/test_person.py:0: error: "str" has no attribute "get"  [attr-defined]
markettor/queries/trends/test/test_person.py:0: error: Invalid index type "int" for "_MonkeyPatchedResponse"; expected type "str"  [index]
markettor/queries/trends/test/test_person.py:0: error: "str" has no attribute "get"  [attr-defined]
markettor/queries/trends/test/test_person.py:0: error: Invalid index type "int" for "_MonkeyPatchedResponse"; expected type "str"  [index]
markettor/queries/trends/test/test_person.py:0: error: "str" has no attribute "get"  [attr-defined]
markettor/queries/trends/test/test_person.py:0: error: Invalid index type "int" for "_MonkeyPatchedResponse"; expected type "str"  [index]
markettor/queries/trends/test/test_person.py:0: error: "str" has no attribute "get"  [attr-defined]
markettor/queries/trends/test/test_person.py:0: error: Invalid index type "int" for "_MonkeyPatchedResponse"; expected type "str"  [index]
markettor/queries/trends/test/test_person.py:0: error: "str" has no attribute "get"  [attr-defined]
markettor/queries/trends/test/test_person.py:0: error: Invalid index type "int" for "_MonkeyPatchedResponse"; expected type "str"  [index]
markettor/queries/trends/test/test_person.py:0: error: "str" has no attribute "get"  [attr-defined]
markettor/queries/trends/test/test_person.py:0: error: Invalid index type "int" for "_MonkeyPatchedResponse"; expected type "str"  [index]
markettor/queries/trends/test/test_person.py:0: error: "str" has no attribute "get"  [attr-defined]
markettor/queries/trends/test/test_person.py:0: error: Invalid index type "int" for "_MonkeyPatchedResponse"; expected type "str"  [index]
markettor/models/test/test_organization_model.py:0: error: Module "django.utils.timezone" does not explicitly export attribute "timedelta"  [attr-defined]
markettor/management/commands/sync_persons_to_clickhouse.py:0: error: Argument 4 to "create_person_override" has incompatible type "int | None"; expected "int"  [arg-type]
markettor/management/commands/sync_persons_to_clickhouse.py:0: error: Argument "group_type_index" to "raw_create_group_ch" has incompatible type "int"; expected "Literal[0, 1, 2, 3, 4]"  [arg-type]
markettor/management/commands/migrate_team.py:0: error: Incompatible types in assignment (expression has type "None", variable has type "BatchExport")  [assignment]
markettor/management/commands/migrate_team.py:0: error: "BatchExportDestination" has no attribute "exclude_events"  [attr-defined]
markettor/management/commands/migrate_team.py:0: error: "BatchExportDestination" has no attribute "include_events"  [attr-defined]
markettor/management/commands/fix_future_person_created_at.py:0: error: Argument "version" to "create_person" has incompatible type "int | None"; expected "int"  [arg-type]
markettor/hogql_queries/test/test_actors_query_runner.py:0: error: Incompatible types in assignment (expression has type "Expr", variable has type "SelectQuery")  [assignment]
markettor/hogql/test/test_resolver.py:0: error: Item "None" of "JoinExpr | None" has no attribute "next_join"  [union-attr]
markettor/hogql/test/test_resolver.py:0: error: Item "None" of "JoinExpr | Any | None" has no attribute "constraint"  [union-attr]
markettor/hogql/test/test_resolver.py:0: error: Item "None" of "JoinConstraint | Any | None" has no attribute "constraint_type"  [union-attr]
markettor/hogql/test/test_resolver.py:0: error: Item "None" of "JoinConstraint | Any | None" has no attribute "expr"  [union-attr]
markettor/hogql/test/test_resolver.py:0: error: Item "None" of "JoinExpr | None" has no attribute "next_join"  [union-attr]
markettor/hogql/test/test_resolver.py:0: error: Item "None" of "JoinExpr | Any | None" has no attribute "constraint"  [union-attr]
markettor/hogql/test/test_resolver.py:0: error: Item "None" of "JoinConstraint | Any | None" has no attribute "constraint_type"  [union-attr]
markettor/hogql/test/test_resolver.py:0: error: Item "SelectUnionQueryType" of "SelectQueryType | SelectUnionQueryType | None" has no attribute "columns"  [union-attr]
markettor/hogql/test/test_resolver.py:0: error: Item "None" of "SelectQueryType | SelectUnionQueryType | None" has no attribute "columns"  [union-attr]
markettor/hogql/test/test_resolver.py:0: error: "FieldOrTable" has no attribute "fields"  [attr-defined]
markettor/hogql/test/test_resolver.py:0: error: "FieldOrTable" has no attribute "fields"  [attr-defined]
markettor/hogql/test/test_resolver.py:0: error: "FieldOrTable" has no attribute "fields"  [attr-defined]
markettor/hogql/test/test_resolver.py:0: error: Item "None" of "JoinExpr | None" has no attribute "table"  [union-attr]
markettor/hogql/test/test_resolver.py:0: error: Argument 1 to "clone_expr" has incompatible type "SelectQuery | SelectUnionQuery | Field | Any | None"; expected "Expr"  [arg-type]
markettor/hogql/test/test_resolver.py:0: error: Item "None" of "JoinExpr | None" has no attribute "alias"  [union-attr]
markettor/hogql/test/test_query.py:0: error: Value of type "list[QueryTiming] | None" is not indexable  [index]
markettor/hogql/test/test_query.py:0: error: Value of type "list[QueryTiming] | None" is not indexable  [index]
markettor/hogql/test/test_query.py:0: error: Module has no attribute "utc"  [attr-defined]
markettor/hogql/test/test_query.py:0: error: Argument 1 to "pretty_print_in_tests" has incompatible type "str | None"; expected "str"  [arg-type]
markettor/hogql/test/test_query.py:0: error: Argument 1 to "pretty_print_in_tests" has incompatible type "str | None"; expected "str"  [arg-type]
markettor/hogql/test/test_query.py:0: error: Argument 1 to "pretty_print_in_tests" has incompatible type "str | None"; expected "str"  [arg-type]
markettor/hogql/test/test_query.py:0: error: Argument 1 to "pretty_print_in_tests" has incompatible type "str | None"; expected "str"  [arg-type]
markettor/hogql/test/test_query.py:0: error: Module has no attribute "utc"  [attr-defined]
markettor/hogql/test/test_query.py:0: error: Module has no attribute "utc"  [attr-defined]
markettor/hogql/test/test_query.py:0: error: Module has no attribute "utc"  [attr-defined]
markettor/hogql/test/test_query.py:0: error: Module has no attribute "utc"  [attr-defined]
markettor/hogql/test/test_query.py:0: error: Module has no attribute "utc"  [attr-defined]
markettor/hogql/test/test_query.py:0: error: Module has no attribute "utc"  [attr-defined]
markettor/hogql/test/test_query.py:0: error: Module has no attribute "utc"  [attr-defined]
markettor/hogql/test/test_query.py:0: error: Module has no attribute "utc"  [attr-defined]
markettor/hogql/test/test_query.py:0: error: Argument "placeholders" to "execute_hogql_query" has incompatible type "dict[str, Constant]"; expected "dict[str, Expr] | None"  [arg-type]
markettor/hogql/test/test_query.py:0: note: "Dict" is invariant -- see https://mypy.readthedocs.io/en/stable/common_issues.html#variance
markettor/hogql/test/test_query.py:0: note: Consider using "Mapping" instead, which is covariant in the value type
markettor/hogql/test/test_query.py:0: error: Argument 1 to "pretty_print_in_tests" has incompatible type "str | None"; expected "str"  [arg-type]
markettor/hogql/test/test_query.py:0: error: Argument "placeholders" to "execute_hogql_query" has incompatible type "dict[str, Constant]"; expected "dict[str, Expr] | None"  [arg-type]
markettor/hogql/test/test_query.py:0: note: "Dict" is invariant -- see https://mypy.readthedocs.io/en/stable/common_issues.html#variance
markettor/hogql/test/test_query.py:0: note: Consider using "Mapping" instead, which is covariant in the value type
markettor/hogql/test/test_query.py:0: error: Argument 1 to "pretty_print_in_tests" has incompatible type "str | None"; expected "str"  [arg-type]
markettor/hogql/test/test_query.py:0: error: Argument "placeholders" to "execute_hogql_query" has incompatible type "dict[str, Constant]"; expected "dict[str, Expr] | None"  [arg-type]
markettor/hogql/test/test_query.py:0: note: "Dict" is invariant -- see https://mypy.readthedocs.io/en/stable/common_issues.html#variance
markettor/hogql/test/test_query.py:0: note: Consider using "Mapping" instead, which is covariant in the value type
markettor/hogql/test/test_parser_python.py:0: error: Unsupported dynamic base class "parser_test_factory"  [misc]
markettor/hogql/test/test_parser_cpp.py:0: error: Unsupported dynamic base class "parser_test_factory"  [misc]
markettor/hogql/test/test_parse_string_python.py:0: error: Unsupported dynamic base class "parse_string_test_factory"  [misc]
markettor/hogql/test/test_parse_string_cpp.py:0: error: Unsupported dynamic base class "parse_string_test_factory"  [misc]
markettor/hogql/functions/test/test_cohort.py:0: error: "TestCohort" has no attribute "snapshot"  [attr-defined]
markettor/hogql/functions/test/test_cohort.py:0: error: "TestCohort" has no attribute "snapshot"  [attr-defined]
markettor/hogql/functions/test/test_cohort.py:0: error: "TestCohort" has no attribute "snapshot"  [attr-defined]
markettor/hogql/database/test/test_view.py:0: error: Argument "dialect" to "print_ast" has incompatible type "str"; expected "Literal['hogql', 'clickhouse']"  [arg-type]
markettor/hogql/database/test/test_s3_table.py:0: error: Argument "dialect" to "print_ast" has incompatible type "str"; expected "Literal['hogql', 'clickhouse']"  [arg-type]
markettor/async_migrations/test/test_runner.py:0: error: Item "None" of "datetime | None" has no attribute "day"  [union-attr]
markettor/api/test/test_insight.py:0: error: Argument "data" to "get" of "APIClient" has incompatible type "dict[str, object]"; expected "Mapping[str, str | bytes | int | Iterable[str | bytes | int]] | Iterable[tuple[str, str | bytes | int | Iterable[str | bytes | int]]] | None"  [arg-type]
markettor/api/test/test_insight.py:0: error: Argument "data" to "get" of "APIClient" has incompatible type "dict[str, object]"; expected "Mapping[str, str | bytes | int | Iterable[str | bytes | int]] | Iterable[tuple[str, str | bytes | int | Iterable[str | bytes | int]]] | None"  [arg-type]
markettor/api/test/test_feature_flag.py:0: error: Item "None" of "Dashboard | None" has no attribute "tiles"  [union-attr]
markettor/api/test/test_feature_flag.py:0: error: Item "None" of "Dashboard | None" has no attribute "name"  [union-attr]
markettor/api/test/test_feature_flag.py:0: error: Item "None" of "Dashboard | None" has no attribute "description"  [union-attr]
markettor/api/test/test_feature_flag.py:0: error: Item "None" of "Dashboard | None" has no attribute "filters"  [union-attr]
markettor/api/test/test_feature_flag.py:0: error: Item "None" of "Dashboard | None" has no attribute "tiles"  [union-attr]
markettor/api/test/test_feature_flag.py:0: error: Item "None" of "Dashboard | None" has no attribute "name"  [union-attr]
markettor/api/test/test_feature_flag.py:0: error: Item "None" of "Dashboard | None" has no attribute "description"  [union-attr]
markettor/api/test/test_feature_flag.py:0: error: Item "None" of "Dashboard | None" has no attribute "filters"  [union-attr]
markettor/api/test/dashboards/test_dashboard.py:0: error: Value of type variable "_S" of "assertAlmostEqual" of "TestCase" cannot be "datetime | None"  [type-var]
markettor/api/test/dashboards/test_dashboard.py:0: error: Module "django.utils.timezone" does not explicitly export attribute "timedelta"  [attr-defined]
markettor/api/test/dashboards/test_dashboard.py:0: error: Module "django.utils.timezone" does not explicitly export attribute "timedelta"  [attr-defined]
markettor/api/test/dashboards/test_dashboard.py:0: error: Module "django.utils.timezone" does not explicitly export attribute "timedelta"  [attr-defined]
markettor/api/search.py:0: error: Argument "klass" to "class_queryset" has incompatible type "object"; expected "type[Model]"  [arg-type]
markettor/api/search.py:0: error: Argument "search_fields" to "class_queryset" has incompatible type "object"; expected "dict[str, str]"  [arg-type]
markettor/api/search.py:0: error: Argument "extra_fields" to "class_queryset" has incompatible type "object"; expected "dict[Any, Any] | None"  [arg-type]
markettor/api/search.py:0: error: "type[Model]" has no attribute "objects"  [attr-defined]
markettor/api/search.py:0: error: Argument 1 to "reduce" has incompatible type "Callable[[SearchVector, SearchVector], CombinedExpression]"; expected "Callable[[SearchVector, SearchVector], SearchVector]"  [arg-type]
markettor/api/search.py:0: error: Incompatible return value type (got "CombinedExpression", expected "SearchVector")  [return-value]
markettor/api/property_definition.py:0: error: Item "AnonymousUser" of "User | AnonymousUser" has no attribute "organization"  [union-attr]
markettor/api/property_definition.py:0: error: Item "None" of "Organization | Any | None" has no attribute "is_feature_available"  [union-attr]
markettor/api/property_definition.py:0: error: Item "ForeignObjectRel" of "Field[Any, Any] | ForeignObjectRel | GenericForeignKey" has no attribute "cached_col"  [union-attr]
markettor/api/property_definition.py:0: error: Item "GenericForeignKey" of "Field[Any, Any] | ForeignObjectRel | GenericForeignKey" has no attribute "cached_col"  [union-attr]
markettor/api/property_definition.py:0: error: Incompatible types in assignment (expression has type "Manager[EnterprisePropertyDefinition]", variable has type "QuerySet[PropertyDefinition, PropertyDefinition]")  [assignment]
markettor/api/property_definition.py:0: error: Item "BasePagination" of "BasePagination | None" has no attribute "get_limit"  [union-attr]
markettor/api/property_definition.py:0: error: Item "None" of "BasePagination | None" has no attribute "get_limit"  [union-attr]
markettor/api/property_definition.py:0: error: Item "BasePagination" of "BasePagination | None" has no attribute "get_offset"  [union-attr]
markettor/api/property_definition.py:0: error: Item "None" of "BasePagination | None" has no attribute "get_offset"  [union-attr]
markettor/api/property_definition.py:0: error: Item "BasePagination" of "BasePagination | None" has no attribute "set_count"  [union-attr]
markettor/api/property_definition.py:0: error: Item "None" of "BasePagination | None" has no attribute "set_count"  [union-attr]
markettor/api/property_definition.py:0: error: Item "AnonymousUser" of "User | AnonymousUser" has no attribute "organization"  [union-attr]
markettor/api/property_definition.py:0: error: Item "None" of "Organization | Any | None" has no attribute "is_feature_available"  [union-attr]
markettor/api/property_definition.py:0: error: Incompatible types in assignment (expression has type "type[EnterprisePropertyDefinitionSerializer]", variable has type "type[PropertyDefinitionSerializer]")  [assignment]
markettor/api/property_definition.py:0: error: Item "AnonymousUser" of "User | AnonymousUser" has no attribute "organization"  [union-attr]
markettor/api/property_definition.py:0: error: Item "None" of "Organization | Any | None" has no attribute "is_feature_available"  [union-attr]
markettor/api/event.py:0: error: Argument 1 to <tuple> has incompatible type "*tuple[str, ...]"; expected "type[BaseRenderer]"  [arg-type]
markettor/admin/inlines/plugin_attachment_inline.py:0: error: Signature of "has_add_permission" incompatible with supertype "BaseModelAdmin"  [override]
markettor/admin/inlines/plugin_attachment_inline.py:0: note: Superclass:
markettor/admin/inlines/plugin_attachment_inline.py:0: note: def has_add_permission(self, request: HttpRequest) -> bool
markettor/admin/inlines/plugin_attachment_inline.py:0: note: Subclass:
markettor/admin/inlines/plugin_attachment_inline.py:0: note: def has_add_permission(self, request: Any, obj: Any) -> Any
markettor/admin/inlines/plugin_attachment_inline.py:0: error: Signature of "has_change_permission" incompatible with supertype "InlineModelAdmin"  [override]
markettor/admin/inlines/plugin_attachment_inline.py:0: note: Superclass:
markettor/admin/inlines/plugin_attachment_inline.py:0: note: def has_change_permission(self, request: HttpRequest, obj: Any | None = ...) -> bool
markettor/admin/inlines/plugin_attachment_inline.py:0: note: Subclass:
markettor/admin/inlines/plugin_attachment_inline.py:0: note: def has_change_permission(self, request: Any, obj: Any) -> Any
markettor/admin/inlines/plugin_attachment_inline.py:0: error: Signature of "has_change_permission" incompatible with supertype "BaseModelAdmin"  [override]
markettor/admin/inlines/plugin_attachment_inline.py:0: note: Superclass:
markettor/admin/inlines/plugin_attachment_inline.py:0: note: def has_change_permission(self, request: HttpRequest, obj: Any | None = ...) -> bool
markettor/admin/inlines/plugin_attachment_inline.py:0: note: Subclass:
markettor/admin/inlines/plugin_attachment_inline.py:0: note: def has_change_permission(self, request: Any, obj: Any) -> Any
markettor/admin/inlines/plugin_attachment_inline.py:0: error: Signature of "has_delete_permission" incompatible with supertype "InlineModelAdmin"  [override]
markettor/admin/inlines/plugin_attachment_inline.py:0: note: Superclass:
markettor/admin/inlines/plugin_attachment_inline.py:0: note: def has_delete_permission(self, request: HttpRequest, obj: Any | None = ...) -> bool
markettor/admin/inlines/plugin_attachment_inline.py:0: note: Subclass:
markettor/admin/inlines/plugin_attachment_inline.py:0: note: def has_delete_permission(self, request: Any, obj: Any) -> Any
markettor/admin/inlines/plugin_attachment_inline.py:0: error: Signature of "has_delete_permission" incompatible with supertype "BaseModelAdmin"  [override]
markettor/admin/inlines/plugin_attachment_inline.py:0: note: Superclass:
markettor/admin/inlines/plugin_attachment_inline.py:0: note: def has_delete_permission(self, request: HttpRequest, obj: Any | None = ...) -> bool
markettor/admin/inlines/plugin_attachment_inline.py:0: note: Subclass:
markettor/admin/inlines/plugin_attachment_inline.py:0: note: def has_delete_permission(self, request: Any, obj: Any) -> Any
markettor/admin/admins/team_admin.py:0: error: Item "None" of "Project | None" has no attribute "pk"  [union-attr]
markettor/admin/admins/team_admin.py:0: error: Item "None" of "Project | None" has no attribute "name"  [union-attr]
markettor/admin/admins/plugin_admin.py:0: error: Item "None" of "Organization | None" has no attribute "pk"  [union-attr]
markettor/admin/admins/plugin_admin.py:0: error: Item "None" of "Organization | None" has no attribute "name"  [union-attr]
ee/clickhouse/views/experiments.py:0: error: Argument 4 to "ClickhouseTrendExperimentResult" has incompatible type "datetime | None"; expected "datetime"  [arg-type]
ee/clickhouse/views/experiments.py:0: error: Argument 4 to "ClickhouseFunnelExperimentResult" has incompatible type "datetime | None"; expected "datetime"  [arg-type]
ee/clickhouse/views/experiments.py:0: error: Argument 4 to "ClickhouseSecondaryExperimentResult" has incompatible type "datetime | None"; expected "datetime"  [arg-type]
ee/clickhouse/views/experiments.py:0: error: Item "None" of "User | None" has no attribute "email"  [union-attr]
markettor/temporal/data_imports/workflow_activities/create_job_model.py:0: error: Argument 1 has incompatible type "str"; expected "Type"  [arg-type]
markettor/temporal/data_imports/workflow_activities/create_job_model.py:0: error: Incompatible types in assignment (expression has type "list[Any]", variable has type "dict[str, list[tuple[str, str]]]")  [assignment]
markettor/temporal/data_imports/workflow_activities/create_job_model.py:0: error: No overload variant of "get" of "dict" matches argument types "str", "tuple[()]"  [call-overload]
markettor/temporal/data_imports/workflow_activities/create_job_model.py:0: note: Possible overload variants:
markettor/temporal/data_imports/workflow_activities/create_job_model.py:0: note: def get(self, Type, /) -> Sequence[str] | None
markettor/temporal/data_imports/workflow_activities/create_job_model.py:0: note: def get(self, Type, Sequence[str], /) -> Sequence[str]
markettor/temporal/data_imports/workflow_activities/create_job_model.py:0: note: def [_T] get(self, Type, _T, /) -> Sequence[str] | _T
markettor/temporal/data_imports/workflow_activities/create_job_model.py:0: error: Argument 1 has incompatible type "dict[str, list[tuple[str, str]]]"; expected "list[Any]"  [arg-type]
markettor/session_recordings/session_recording_api.py:0: error: Argument "team_id" to "get_realtime_snapshots" has incompatible type "int"; expected "str"  [arg-type]
markettor/session_recordings/session_recording_api.py:0: error: Value of type variable "SupportsRichComparisonT" of "sorted" cannot be "str | None"  [type-var]
markettor/session_recordings/session_recording_api.py:0: error: Argument 1 to "get" of "dict" has incompatible type "str | None"; expected "str"  [arg-type]
markettor/queries/app_metrics/test/test_app_metrics.py:0: error: Argument 3 to "AppMetricsErrorDetailsQuery" has incompatible type "AppMetricsRequestSerializer"; expected "AppMetricsErrorsRequestSerializer"  [arg-type]
markettor/queries/app_metrics/test/test_app_metrics.py:0: error: Argument 3 to "AppMetricsErrorDetailsQuery" has incompatible type "AppMetricsRequestSerializer"; expected "AppMetricsErrorsRequestSerializer"  [arg-type]
markettor/queries/app_metrics/test/test_app_metrics.py:0: error: Argument 3 to "AppMetricsErrorDetailsQuery" has incompatible type "AppMetricsRequestSerializer"; expected "AppMetricsErrorsRequestSerializer"  [arg-type]
markettor/queries/app_metrics/historical_exports.py:0: error: Argument 1 to "loads" has incompatible type "str | None"; expected "str | bytes | bytearray"  [arg-type]
markettor/api/test/test_decide.py:0: error: Item "None" of "User | None" has no attribute "toolbar_mode"  [union-attr]
markettor/api/test/test_decide.py:0: error: Item "None" of "User | None" has no attribute "save"  [union-attr]
markettor/api/test/test_authentication.py:0: error: Module has no attribute "utc"  [attr-defined]
markettor/admin/admins/plugin_config_admin.py:0: error: Item "None" of "Team | None" has no attribute "name"  [union-attr]
markettor/migrations/0237_remove_timezone_from_teams.py:0: error: Argument 2 to "RunPython" has incompatible type "Callable[[Migration, Any], None]"; expected "_CodeCallable | None"  [arg-type]
markettor/migrations/0228_fix_tile_layouts.py:0: error: Argument 2 to "RunPython" has incompatible type "Callable[[Migration, Any], None]"; expected "_CodeCallable | None"  [arg-type]
markettor/warehouse/external_data_source/source.py:0: error: Incompatible types in assignment (expression has type "int", target has type "str")  [assignment]
markettor/warehouse/external_data_source/source.py:0: error: Incompatible types in assignment (expression has type "int", target has type "str")  [assignment]
markettor/warehouse/external_data_source/source.py:0: error: Incompatible types in assignment (expression has type "dict[str, Collection[str]]", variable has type "StripeSourcePayload")  [assignment]
markettor/warehouse/external_data_source/source.py:0: error: Argument 1 to "_create_source" has incompatible type "StripeSourcePayload"; expected "dict[Any, Any]"  [arg-type]
markettor/api/sharing.py:0: error: Item "None" of "list[Any] | None" has no attribute "__iter__" (not iterable)  [union-attr]
markettor/api/plugin.py:0: error: Item "None" of "Team | None" has no attribute "organization"  [union-attr]
markettor/api/plugin.py:0: error: Item "None" of "Team | None" has no attribute "id"  [union-attr]
markettor/api/plugin.py:0: error: Item "None" of "Team | None" has no attribute "organization"  [union-attr]
markettor/api/plugin.py:0: error: Item "None" of "Team | None" has no attribute "id"  [union-attr]
markettor/api/plugin.py:0: error: Incompatible types in assignment (expression has type "str | None", variable has type "str | int | Combinable")  [assignment]
markettor/api/plugin.py:0: error: Incompatible types in assignment (expression has type "str | None", variable has type "str | int | Combinable")  [assignment]
markettor/api/plugin.py:0: error: Incompatible types in assignment (expression has type "int | None", variable has type "float | int | str | Combinable")  [assignment]
markettor/api/plugin.py:0: error: Item "None" of "IO[Any] | None" has no attribute "read"  [union-attr]
markettor/api/plugin.py:0: error: Incompatible type for "file_name" of "PluginAttachment" (got "str | None", expected "str | int | Combinable")  [misc]
markettor/api/plugin.py:0: error: Incompatible type for "file_size" of "PluginAttachment" (got "int | None", expected "float | int | str | Combinable")  [misc]
markettor/api/plugin.py:0: error: Item "None" of "IO[Any] | None" has no attribute "read"  [union-attr]
markettor/api/plugin.py:0: error: Item "None" of "Team | None" has no attribute "organization"  [union-attr]
markettor/api/plugin.py:0: error: Item "None" of "Team | None" has no attribute "id"  [union-attr]
markettor/temporal/tests/batch_exports/test_run_updates.py:0: error: Unused "type: ignore" comment  [unused-ignore]
markettor/temporal/tests/batch_exports/test_run_updates.py:0: error: Unused "type: ignore" comment  [unused-ignore]
markettor/temporal/tests/batch_exports/test_run_updates.py:0: error: Unused "type: ignore" comment  [unused-ignore]
markettor/temporal/tests/batch_exports/test_run_updates.py:0: error: Unused "type: ignore" comment  [unused-ignore]
markettor/temporal/tests/batch_exports/test_batch_exports.py:0: error: TypedDict key must be a string literal; expected one of ("_timestamp", "created_at", "distinct_id", "elements", "elements_chain", ...)  [literal-required]
markettor/api/plugin_log_entry.py:0: error: Name "timezone.datetime" is not defined  [name-defined]
markettor/api/plugin_log_entry.py:0: error: Module "django.utils.timezone" does not explicitly export attribute "datetime"  [attr-defined]
markettor/api/plugin_log_entry.py:0: error: Name "timezone.datetime" is not defined  [name-defined]
markettor/api/plugin_log_entry.py:0: error: Module "django.utils.timezone" does not explicitly export attribute "datetime"  [attr-defined]
markettor/temporal/data_imports/pipelines/rest_source/config_setup.py:0: error: Dict entry 2 has incompatible type "Literal['auto']": "None"; expected "Literal['json_response', 'header_link', 'auto', 'single_page', 'cursor', 'offset', 'page_number']": "type[BasePaginator]"  [dict-item]
markettor/temporal/data_imports/pipelines/rest_source/config_setup.py:0: error: Incompatible types in assignment (expression has type "None", variable has type "AuthConfigBase")  [assignment]
markettor/temporal/data_imports/pipelines/rest_source/config_setup.py:0: error: Argument 1 to "get_auth_class" has incompatible type "Literal['bearer', 'api_key', 'http_basic'] | None"; expected "Literal['bearer', 'api_key', 'http_basic']"  [arg-type]
markettor/temporal/data_imports/pipelines/rest_source/config_setup.py:0: error: Need type annotation for "dependency_graph"  [var-annotated]
markettor/temporal/data_imports/pipelines/rest_source/config_setup.py:0: error: Incompatible types in assignment (expression has type "None", target has type "ResolvedParam")  [assignment]
markettor/temporal/data_imports/pipelines/rest_source/config_setup.py:0: error: Incompatible return value type (got "tuple[TopologicalSorter[Any], dict[str, EndpointResource], dict[str, ResolvedParam]]", expected "tuple[Any, dict[str, EndpointResource], dict[str, ResolvedParam | None]]")  [return-value]
markettor/temporal/data_imports/pipelines/rest_source/config_setup.py:0: error: Unsupported right operand type for in ("str | Endpoint | None")  [operator]
markettor/temporal/data_imports/pipelines/rest_source/config_setup.py:0: error: Value of type variable "StrOrLiteralStr" of "parse" of "Formatter" cannot be "str | None"  [type-var]
markettor/temporal/data_imports/pipelines/rest_source/config_setup.py:0: error: Unsupported right operand type for in ("dict[str, ResolveParamConfig | IncrementalParamConfig | Any] | None")  [operator]
markettor/temporal/data_imports/pipelines/rest_source/config_setup.py:0: error: Unsupported right operand type for in ("dict[str, ResolveParamConfig | IncrementalParamConfig | Any] | None")  [operator]
markettor/temporal/data_imports/pipelines/rest_source/config_setup.py:0: error: Value of type "dict[str, ResolveParamConfig | IncrementalParamConfig | Any] | None" is not indexable  [index]
markettor/temporal/data_imports/pipelines/rest_source/config_setup.py:0: error: Item "None" of "dict[str, ResolveParamConfig | IncrementalParamConfig | Any] | None" has no attribute "pop"  [union-attr]
markettor/temporal/data_imports/pipelines/rest_source/config_setup.py:0: error: Value of type "dict[str, ResolveParamConfig | IncrementalParamConfig | Any] | None" is not indexable  [index]
markettor/temporal/data_imports/pipelines/rest_source/config_setup.py:0: error: Item "None" of "str | None" has no attribute "format"  [union-attr]
markettor/temporal/data_imports/pipelines/rest_source/config_setup.py:0: error: Argument 1 to "single_entity_path" has incompatible type "str | None"; expected "str"  [arg-type]
markettor/temporal/data_imports/pipelines/rest_source/config_setup.py:0: error: Item "None" of "dict[str, ResolveParamConfig | IncrementalParamConfig | Any] | None" has no attribute "items"  [union-attr]
markettor/temporal/data_imports/pipelines/rest_source/config_setup.py:0: error: Incompatible types in assignment (expression has type "str | None", variable has type "str")  [assignment]
markettor/temporal/data_imports/pipelines/rest_source/config_setup.py:0: error: Incompatible types in assignment (expression has type "str | None", variable has type "str")  [assignment]
markettor/temporal/data_imports/pipelines/rest_source/config_setup.py:0: error: Statement is unreachable  [unreachable]
markettor/temporal/data_imports/pipelines/rest_source/config_setup.py:0: error: Unpacked dict entry 0 has incompatible type "dict[str, Any] | None"; expected "SupportsKeysAndGetItem[str, Any]"  [dict-item]
markettor/temporal/data_imports/pipelines/rest_source/config_setup.py:0: error: Unpacked dict entry 1 has incompatible type "dict[str, Any] | None"; expected "SupportsKeysAndGetItem[str, Any]"  [dict-item]
markettor/temporal/data_imports/pipelines/rest_source/config_setup.py:0: error: Unpacked dict entry 0 has incompatible type "dict[str, Any] | None"; expected "SupportsKeysAndGetItem[str, ResolveParamConfig | IncrementalParamConfig | Any]"  [dict-item]
markettor/temporal/data_imports/pipelines/rest_source/config_setup.py:0: error: Unpacked dict entry 1 has incompatible type "dict[str, ResolveParamConfig | IncrementalParamConfig | Any] | None"; expected "SupportsKeysAndGetItem[str, ResolveParamConfig | IncrementalParamConfig | Any]"  [dict-item]
markettor/temporal/tests/batch_exports/test_snowflake_batch_export_workflow.py:0: error: Need type annotation for "_execute_calls" (hint: "_execute_calls: list[<type>] = ...")  [var-annotated]
markettor/temporal/tests/batch_exports/test_snowflake_batch_export_workflow.py:0: error: Need type annotation for "_execute_async_calls" (hint: "_execute_async_calls: list[<type>] = ...")  [var-annotated]
markettor/temporal/tests/batch_exports/test_snowflake_batch_export_workflow.py:0: error: Need type annotation for "_cursors" (hint: "_cursors: list[<type>] = ...")  [var-annotated]
markettor/temporal/tests/batch_exports/test_snowflake_batch_export_workflow.py:0: error: List item 0 has incompatible type "tuple[str, str, int, int, int, int, str, int]"; expected "tuple[str, str, int, int, str, str, str, str]"  [list-item]
markettor/temporal/tests/batch_exports/test_s3_batch_export_workflow.py:0: error: "tuple[Any, ...]" has no attribute "last_uploaded_part_timestamp"  [attr-defined]
markettor/temporal/tests/batch_exports/test_s3_batch_export_workflow.py:0: error: "tuple[Any, ...]" has no attribute "upload_state"  [attr-defined]
markettor/temporal/tests/batch_exports/test_redshift_batch_export_workflow.py:0: error: Incompatible types in assignment (expression has type "str | int", variable has type "int")  [assignment]
markettor/temporal/data_imports/pipelines/rest_source/__init__.py:0: error: Not all union combinations were tried because there are too many unions  [misc]
markettor/temporal/data_imports/pipelines/rest_source/__init__.py:0: error: Argument 2 to "source" has incompatible type "str | None"; expected "str"  [arg-type]
markettor/temporal/data_imports/pipelines/rest_source/__init__.py:0: error: Argument 3 to "source" has incompatible type "str | None"; expected "str"  [arg-type]
markettor/temporal/data_imports/pipelines/rest_source/__init__.py:0: error: Argument 4 to "source" has incompatible type "int | None"; expected "int"  [arg-type]
markettor/temporal/data_imports/pipelines/rest_source/__init__.py:0: error: Argument 6 to "source" has incompatible type "Schema | None"; expected "Schema"  [arg-type]
markettor/temporal/data_imports/pipelines/rest_source/__init__.py:0: error: Argument 7 to "source" has incompatible type "Literal['evolve', 'discard_value', 'freeze', 'discard_row'] | TSchemaContractDict | None"; expected "Literal['evolve', 'discard_value', 'freeze', 'discard_row'] | TSchemaContractDict"  [arg-type]
markettor/temporal/data_imports/pipelines/rest_source/__init__.py:0: error: Argument 8 to "source" has incompatible type "type[BaseConfiguration] | None"; expected "type[BaseConfiguration]"  [arg-type]
markettor/temporal/data_imports/pipelines/rest_source/__init__.py:0: error: Argument 1 to "build_resource_dependency_graph" has incompatible type "EndpointResourceBase | None"; expected "EndpointResourceBase"  [arg-type]
markettor/temporal/data_imports/pipelines/rest_source/__init__.py:0: error: Incompatible types in assignment (expression has type "list[str] | None", variable has type "list[str]")  [assignment]
markettor/temporal/data_imports/pipelines/rest_source/__init__.py:0: error: Argument 1 to "setup_incremental_object" has incompatible type "dict[str, ResolveParamConfig | IncrementalParamConfig | Any] | None"; expected "dict[str, Any]"  [arg-type]
markettor/temporal/data_imports/pipelines/rest_source/__init__.py:0: error: Argument "base_url" to "RESTClient" has incompatible type "str | None"; expected "str"  [arg-type]
markettor/temporal/data_imports/pipelines/rest_source/__init__.py:0: error: Argument 1 to "exclude_keys" has incompatible type "dict[str, ResolveParamConfig | IncrementalParamConfig | Any] | None"; expected "Mapping[str, Any]"  [arg-type]
markettor/temporal/data_imports/pipelines/rest_source/__init__.py:0: error: Incompatible default for argument "resolved_param" (default has type "ResolvedParam | None", argument has type "ResolvedParam")  [assignment]
markettor/temporal/data_imports/pipelines/rest_source/__init__.py:0: error: Unused "type: ignore" comment  [unused-ignore]
markettor/temporal/data_imports/pipelines/rest_source/__init__.py:0: error: Argument "module" to "SourceInfo" has incompatible type Module | None; expected Module  [arg-type]
markettor/temporal/data_imports/pipelines/zendesk/__init__.py:0: error: Unused "type: ignore" comment  [unused-ignore]
markettor/temporal/data_imports/pipelines/zendesk/__init__.py:0: error: Unused "type: ignore" comment  [unused-ignore]
markettor/temporal/data_imports/pipelines/zendesk/__init__.py:0: error: Unused "type: ignore" comment  [unused-ignore]
markettor/temporal/data_imports/pipelines/zendesk/__init__.py:0: error: Unused "type: ignore" comment  [unused-ignore]
markettor/temporal/data_imports/pipelines/zendesk/__init__.py:0: error: Unused "type: ignore" comment  [unused-ignore]
markettor/temporal/data_imports/pipelines/zendesk/__init__.py:0: error: Unused "type: ignore" comment  [unused-ignore]
markettor/temporal/data_imports/pipelines/zendesk/__init__.py:0: error: Unused "type: ignore" comment  [unused-ignore]
markettor/temporal/data_imports/pipelines/zendesk/__init__.py:0: error: Unused "type: ignore" comment  [unused-ignore]
markettor/temporal/data_imports/pipelines/zendesk/__init__.py:0: error: Unused "type: ignore" comment  [unused-ignore]
markettor/temporal/data_imports/pipelines/vitally/__init__.py:0: error: Unused "type: ignore" comment  [unused-ignore]
markettor/temporal/data_imports/pipelines/vitally/__init__.py:0: error: Unused "type: ignore" comment  [unused-ignore]
markettor/temporal/data_imports/pipelines/vitally/__init__.py:0: error: Unused "type: ignore" comment  [unused-ignore]
markettor/temporal/data_imports/pipelines/vitally/__init__.py:0: error: Unused "type: ignore" comment  [unused-ignore]
markettor/temporal/data_imports/pipelines/vitally/__init__.py:0: error: Unused "type: ignore" comment  [unused-ignore]
markettor/temporal/data_imports/pipelines/vitally/__init__.py:0: error: Unused "type: ignore" comment  [unused-ignore]
markettor/temporal/data_imports/pipelines/vitally/__init__.py:0: error: Unused "type: ignore" comment  [unused-ignore]
markettor/temporal/data_imports/pipelines/vitally/__init__.py:0: error: Unused "type: ignore" comment  [unused-ignore]
markettor/temporal/data_imports/pipelines/vitally/__init__.py:0: error: Unused "type: ignore" comment  [unused-ignore]
markettor/temporal/data_imports/pipelines/stripe/__init__.py:0: error: Unused "type: ignore" comment  [unused-ignore]
markettor/temporal/data_imports/pipelines/stripe/__init__.py:0: error: Unused "type: ignore" comment  [unused-ignore]
markettor/temporal/data_imports/pipelines/stripe/__init__.py:0: error: Unused "type: ignore" comment  [unused-ignore]
markettor/temporal/data_imports/pipelines/stripe/__init__.py:0: error: Unused "type: ignore" comment  [unused-ignore]
markettor/temporal/data_imports/pipelines/stripe/__init__.py:0: error: Unused "type: ignore" comment  [unused-ignore]
markettor/temporal/data_imports/pipelines/stripe/__init__.py:0: error: Unused "type: ignore" comment  [unused-ignore]
markettor/temporal/data_imports/pipelines/stripe/__init__.py:0: error: Unused "type: ignore" comment  [unused-ignore]
markettor/temporal/data_imports/pipelines/stripe/__init__.py:0: error: Unused "type: ignore" comment  [unused-ignore]
markettor/api/test/batch_exports/conftest.py:0: error: Signature of "run" incompatible with supertype "Worker"  [override]
markettor/api/test/batch_exports/conftest.py:0: note: Superclass:
markettor/api/test/batch_exports/conftest.py:0: note: def run(self) -> Coroutine[Any, Any, None]
markettor/api/test/batch_exports/conftest.py:0: note: Subclass:
markettor/api/test/batch_exports/conftest.py:0: note: def run(self, loop: Any) -> Any
markettor/api/test/batch_exports/conftest.py:0: error: Argument "activities" to "ThreadedWorker" has incompatible type "list[function]"; expected "Sequence[Callable[..., Any]]"  [arg-type]
markettor/warehouse/api/external_data_schema.py:0: error: Incompatible return value type (got "str | None", expected "SyncType | None")  [return-value]
markettor/warehouse/api/external_data_schema.py:0: error: Argument 1 to "get_sql_schemas_for_source_type" has incompatible type "str"; expected "Type"  [arg-type]
markettor/warehouse/api/external_data_schema.py:0: error: No overload variant of "get" of "dict" matches argument type "str"  [call-overload]
markettor/warehouse/api/external_data_schema.py:0: note: Possible overload variants:
markettor/warehouse/api/external_data_schema.py:0: note: def get(self, Type, /) -> dict[str, list[IncrementalField]] | None
markettor/warehouse/api/external_data_schema.py:0: note: def get(self, Type, dict[str, list[IncrementalField]], /) -> dict[str, list[IncrementalField]]
markettor/warehouse/api/external_data_schema.py:0: note: def [_T] get(self, Type, _T, /) -> dict[str, list[IncrementalField]] | _T
markettor/warehouse/api/table.py:0: error: Unused "type: ignore" comment  [unused-ignore]
markettor/warehouse/api/table.py:0: error: Unused "type: ignore" comment  [unused-ignore]
markettor/warehouse/api/table.py:0: error: Unused "type: ignore" comment  [unused-ignore]
markettor/temporal/data_imports/workflow_activities/import_data.py:0: error: Argument "job_type" to "PipelineInputs" has incompatible type "str"; expected "Type"  [arg-type]
markettor/temporal/data_imports/workflow_activities/import_data.py:0: error: Argument "source_type" to "sql_source_for_type" has incompatible type "str"; expected "Type"  [arg-type]
markettor/temporal/data_imports/workflow_activities/import_data.py:0: error: Argument "source_type" to "sql_source_for_type" has incompatible type "str"; expected "Type"  [arg-type]
markettor/api/test/test_team.py:0: error: "HttpResponse" has no attribute "json"  [attr-defined]
markettor/api/test/test_team.py:0: error: "HttpResponse" has no attribute "json"  [attr-defined]
markettor/test/test_middleware.py:0: error: Incompatible types in assignment (expression has type "_MonkeyPatchedWSGIResponse", variable has type "_MonkeyPatchedResponse")  [assignment]
markettor/management/commands/test/test_create_batch_export_from_app.py:0: error: Incompatible return value type (got "dict[str, Collection[str]]", expected "dict[str, str]")  [return-value]
markettor/management/commands/test/test_create_batch_export_from_app.py:0: error: Incompatible types in assignment (expression has type "dict[str, Collection[str]]", variable has type "dict[str, str]")  [assignment]
markettor/management/commands/test/test_create_batch_export_from_app.py:0: error: Unpacked dict entry 1 has incompatible type "str"; expected "SupportsKeysAndGetItem[str, str]"  [dict-item]
markettor/management/commands/test/test_create_batch_export_from_app.py:0: note: "str" is missing following "SupportsKeysAndGetItem" protocol member:
markettor/management/commands/test/test_create_batch_export_from_app.py:0: note: keys
markettor/management/commands/test/test_create_batch_export_from_app.py:0: note: Following member(s) of "str" have conflicts:
markettor/management/commands/test/test_create_batch_export_from_app.py:0: note: Expected:
markettor/management/commands/test/test_create_batch_export_from_app.py:0: note: def __getitem__(self, str, /) -> str
markettor/management/commands/test/test_create_batch_export_from_app.py:0: note: Got:
markettor/management/commands/test/test_create_batch_export_from_app.py:0: note: def __getitem__(self, SupportsIndex | slice, /) -> str
markettor/management/commands/test/test_create_batch_export_from_app.py:0: error: No overload variant of "__getitem__" of "list" matches argument type "str"  [call-overload]
markettor/management/commands/test/test_create_batch_export_from_app.py:0: note: Possible overload variants:
markettor/management/commands/test/test_create_batch_export_from_app.py:0: note: def __getitem__(self, SupportsIndex, /) -> str
markettor/management/commands/test/test_create_batch_export_from_app.py:0: note: def __getitem__(self, slice, /) -> list[str]
markettor/management/commands/test/test_create_batch_export_from_app.py:0: error: No overload variant of "__getitem__" of "list" matches argument type "str"  [call-overload]
markettor/management/commands/test/test_create_batch_export_from_app.py:0: note: Possible overload variants:
markettor/management/commands/test/test_create_batch_export_from_app.py:0: note: def __getitem__(self, SupportsIndex, /) -> str
markettor/management/commands/test/test_create_batch_export_from_app.py:0: note: def __getitem__(self, slice, /) -> list[str]
markettor/management/commands/test/test_create_batch_export_from_app.py:0: error: No overload variant of "__getitem__" of "list" matches argument type "str"  [call-overload]
markettor/management/commands/test/test_create_batch_export_from_app.py:0: note: Possible overload variants:
markettor/management/commands/test/test_create_batch_export_from_app.py:0: note: def __getitem__(self, SupportsIndex, /) -> str
markettor/management/commands/test/test_create_batch_export_from_app.py:0: note: def __getitem__(self, slice, /) -> list[str]
markettor/management/commands/test/test_create_batch_export_from_app.py:0: error: No overload variant of "__getitem__" of "list" matches argument type "str"  [call-overload]
markettor/management/commands/test/test_create_batch_export_from_app.py:0: note: Possible overload variants:
markettor/management/commands/test/test_create_batch_export_from_app.py:0: note: def __getitem__(self, SupportsIndex, /) -> str
markettor/management/commands/test/test_create_batch_export_from_app.py:0: note: def __getitem__(self, slice, /) -> list[str]
markettor/management/commands/test/test_create_batch_export_from_app.py:0: error: No overload variant of "__getitem__" of "list" matches argument type "str"  [call-overload]
markettor/management/commands/test/test_create_batch_export_from_app.py:0: note: Possible overload variants:
markettor/management/commands/test/test_create_batch_export_from_app.py:0: note: def __getitem__(self, SupportsIndex, /) -> str
markettor/management/commands/test/test_create_batch_export_from_app.py:0: note: def __getitem__(self, slice, /) -> list[str]
markettor/management/commands/test/test_create_batch_export_from_app.py:0: error: No overload variant of "__getitem__" of "list" matches argument type "str"  [call-overload]
markettor/management/commands/test/test_create_batch_export_from_app.py:0: note: Possible overload variants:
markettor/management/commands/test/test_create_batch_export_from_app.py:0: note: def __getitem__(self, SupportsIndex, /) -> str
markettor/management/commands/test/test_create_batch_export_from_app.py:0: note: def __getitem__(self, slice, /) -> list[str]
markettor/api/test/batch_exports/test_update.py:0: error: Unsupported target for indexed assignment ("Collection[str]")  [index]
markettor/api/test/batch_exports/test_update.py:0: error: Unsupported target for indexed assignment ("Collection[str]")  [index]
markettor/api/test/batch_exports/test_update.py:0: error: Dict entry 1 has incompatible type "str": "dict[str, Collection[str]]"; expected "str": "str"  [dict-item]
markettor/api/test/batch_exports/test_update.py:0: error: Value of type "BatchExport" is not indexable  [index]
markettor/api/test/batch_exports/test_update.py:0: error: Value of type "BatchExport" is not indexable  [index]
markettor/api/test/batch_exports/test_update.py:0: error: Value of type "BatchExport" is not indexable  [index]
markettor/api/test/batch_exports/test_pause.py:0: error: "batch_export_delete_schedule" does not return a value (it only ever returns None)  [func-returns-value]
markettor/temporal/tests/external_data/test_external_data_job.py:0: error: Invalid index type "str" for "dict[Type, Sequence[str]]"; expected type "Type"  [index]
markettor/temporal/tests/external_data/test_external_data_job.py:0: error: Invalid index type "str" for "dict[Type, Sequence[str]]"; expected type "Type"  [index]
markettor/temporal/tests/external_data/test_external_data_job.py:0: error: Invalid index type "str" for "dict[Type, Sequence[str]]"; expected type "Type"  [index]
markettor/temporal/tests/external_data/test_external_data_job.py:0: error: Invalid index type "str" for "dict[Type, Sequence[str]]"; expected type "Type"  [index]
markettor/temporal/tests/external_data/test_external_data_job.py:0: error: Invalid index type "str" for "dict[Type, Sequence[str]]"; expected type "Type"  [index]
markettor/api/test/test_capture.py:0: error: Statement is unreachable  [unreachable]
markettor/api/test/test_capture.py:0: error: Incompatible return value type (got "_MonkeyPatchedWSGIResponse", expected "HttpResponse")  [return-value]
markettor/api/test/test_capture.py:0: error: Module has no attribute "utc"  [attr-defined]
markettor/api/test/test_capture.py:0: error: Unpacked dict entry 0 has incompatible type "Collection[str]"; expected "SupportsKeysAndGetItem[str, dict[Never, Never]]"  [dict-item]
markettor/api/test/test_capture.py:0: error: Unpacked dict entry 0 has incompatible type "Collection[str]"; expected "SupportsKeysAndGetItem[str, dict[Never, Never]]"  [dict-item]
markettor/api/test/test_capture.py:0: error: Unpacked dict entry 0 has incompatible type "Collection[str]"; expected "SupportsKeysAndGetItem[str, dict[Never, Never]]"  [dict-item]
markettor/api/test/test_capture.py:0: error: Dict entry 0 has incompatible type "str": "float"; expected "str": "int"  [dict-item]
markettor/api/test/test_capture.py:0: error: Dict entry 0 has incompatible type "str": "float"; expected "str": "int"  [dict-item]
markettor/api/test/test_capture.py:0: error: Dict entry 0 has incompatible type "str": "float"; expected "str": "int"  [dict-item]
markettor/api/test/test_capture.py:0: error: Dict entry 0 has incompatible type "str": "float"; expected "str": "int"  [dict-item]
markettor/api/test/test_capture.py:0: error: Dict entry 0 has incompatible type "str": "float"; expected "str": "int"  [dict-item]
markettor/api/test/test_capture.py:0: error: Dict entry 0 has incompatible type "str": "float"; expected "str": "int"  [dict-item]
markettor/temporal/tests/data_imports/test_end_to_end.py:0: error: Unused "type: ignore" comment  [unused-ignore]
